### ISSUE TITLE
Prototype CVR Fetcher/Java Client for Minio/Dremio Data Retrieval

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1007]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Jave Client/CVR Fetcher queries dremio to get a url - use the url to get an object from dremio

**Comment by n1zea144** [comment]
golang code using Arrow flight library
https://github.com/n1zea144/coexpression-service/blob/main/internal/service/arrow_flight.go

Arrow Flight golang docs:
https://pkg.go.dev/github.com/apache/arrow/go/arrow/flight
