### ISSUE TITLE
Failing Darwin Caisis Fetch

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1012]
## Client (Who is making the request)
Backend pipelines
## Issue/Deliverable
Darwin Caisis failing - potential permissions issue?

```
 Caught SqlSyntaxErrorException for select distinct DMT_TIMELINE_BRAINSPINE_V.DMT_PATIENT_ID_BRAINSPINETMLN, DMT_TIMELINE_BRAINSPINE_V.DMP_PATIENT_ID_MIN_BRAINSPINETMLN, DMT_TIMELINE
```

```
Suppressed: com.ibm.db2.jcc.am.SqlException: DB2 SQL Error: SQLCODE=-727, SQLSTATE=56098, SQLERRMC=2;-551
```

Error -551: https://www.ibm.com/support/pages/sqlcode-551-or-sql0551n-when-user-privileges-are-defined-group

**Comment by sheridancbio** [comment]
A request at TheSpot was submitted for this problem:
https://thespot.mskcc.org/esc/?id=sc_request&is_new_order=true&table=sc_request&sys_id=bf9fbc861b806950b555a9f5624bcb0a

Three code modifications were done to elucidate the problem. First, the query was simplified to rule out actual syntax error - a single field query with no "WHERE" clause also failed with the same error as before. Second, the failing query (TIMELINE) was bypassed to attempt other queries to other db2 views. The CLINICAL view also failed with a similar error. Third, both queries were bypassed and then the fetcher completed successfully (running only the email send step).

**Comment by averyniceday** [comment]
Waiting on username/password resolution from Mrun
