### ISSUE TITLE
Fix Additional Validator Issues

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1043]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Validator in meta import passes without errors 
https://cbioportal.slack.com/files/U046T0JMNLU/F04QBG0U16H/meta_import_output.html

- [x] cases_sequenced.txt

- [x] cases_sv.txt

- [ ] data_clinical_sample.txt

- [x] data_mutations_extended.txt

- [x] data_sv.txt

- [x] meta_gene_matrix.txt

**Comment by callachennault** [comment]
$ grep P-0051724-T04-XS1 data_sv.txt | grep FGFR3 | grep TACC3
P-0051724-T04-XS1	SOMATIC	FGFR3	TACC3									4	4			1741325	1808766	Intron of TACC3(+):103bp before exon 11	Intron of FGFR3(+):76bp before exon 18		GRCh37	DUPLICATION	35	7Protein Fusion: in frame  {FGFR3:TACC3}	PRECISE	5to3	FGFR3 (NM_000142) - TACC3 (NM_006342) fusion: c.2275-83:FGFR3_c.1942-112:TACC3dupyes	unknown	67441	1703	2563	0	70			Note: The FGFR3 - TACC3 fusion involves FGFR3 exons 1 - 17 and TACC3 exons 11 - 16. The fusion is predicted to be in frame and includes the kinase domain of FGFR3.
P-0051724-T04-XS1	SOMATIC	FGFR3	TACC3									4	4			1741325	1808766	Intron of TACC3(+):103bp before exon 11	Intron of FGFR3(+):76bp before exon 18		GRCh37	DUPLICATION			Protein Fusion: in frame  {FGFR3:TACC3}	PRECISE	5to3	FGFR3 (NM_000142) - TACC3 (NM_006342) fusion: c.2275-83:FGFR3_c.1942-112:TACC3dup67441	1703	2563	0	70			Note: The FGFR3 - TACC3 fusion involves FGFR3 exons 1 - 17 and TACC3 exons 11 - 16. The fusion is predicted to be in frame and includes the kinase domain of FGFR3.
