### ISSUE TITLE
Setup Dev Node for Onur and Ramya

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1047]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Node is up with required memory
Two system setup scripts run
Root access for Onur

**Comment by sheridancbio** [comment]
data repo sizes examined. Estimated footprint needed for importer today is about 220GB. The biggest repos are datahub (111 GB) and impact (42 GB).
Data volume size will initially be set to 1TB (to allow individual clones of repos in individual curator accounts)

**Comment by sheridancbio** [comment]
The primary database interaction will be to the triage database which is located on the pipelines3 node. That node is in availability zone us-east-1b and in VPC vpc-0003c8f263d7ed5ab in subnet subnet-081312133f83ddd2b (Subnet C)  ... so the new node will be created also in this subnet

**Comment by sheridancbio** [comment]
assigned ip address : ip-10-1-141-115.ec2.internal
created 2 filesystems .. 512 GB for /data and 1024 GB for /home
configured filesystems like this:
fdisk /dev/nvme1n1
used "g" to create GPT partition table
used "n' to make a primary partition (1) of type linux filesystem with full diskspace used
used "w" to write out partition table to device
mkfs -t ext4 /dev/nvme1n1 # this formats a partition as ext4 filesystem .. done twice for the two disks
cd /home ; tar -cvzf /root/ec2-home.tar.gz ec2-user
vim /etc/fstab

added these lines to fstab:
/dev/sdb        /data   ext4    rw      1       2
/dev/sdc        /home   ext4    rw      1       2

mount -a # this mounts the file systems
cd /home ; tar -xvzf /root/ec2-home.tar.gz

Then rebooted the node to make sure filesystems mount properly and login is possible:
reboot now

login was successful

**Comment by sheridancbio** [comment]
installing users and packages on node:
sudo yum update
also ran create users script and setup_system_dependencies scripts.
distributed temporary passwords to Onur and Curators
