### ISSUE TITLE
Provide AZ Descriptions for Certain Clinical Attributes 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1048]
## Client (Who is making the request)
Astra Zeneca
## Issue/Deliverable
Refer to email - all study view attributes

**Comment by n1zea144** [comment]
@averyniceday I updated to field descriptions to be general for CDD consumption.  I don't think all the fields need to be updated, but best to check and see.  Let me know if you have any questions.

https://docs.google.com/spreadsheets/d/12KzvUprYL5Bon7UpHd1HHLABoUHMZuIrq4ZicuVnJFQ/edit?usp=sharing
