### ISSUE TITLE
Generate ProtoBuf/Message Struct for an Annotated Record 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1053]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Model is generated for the message we'll be sending from the "Annotator" component
Potentially send "records"

- [x] Generate Genome Nexus API (5)
- [x] Use Genome Nexus API to interact with Genome Nexus (annotate with FETCH/POST) (3)
- [x] Implement Functionality from Genome Nexus Annotation Pipeline (8)
- [x] Integrate Annotator function into MPATH-proxy - Iterate through variants and send requests (3)
- [x] Stitch results together as annotated records (5)

**Comment by mandawilson** [comment]
Generate go code for the GenomeNexus API: https://openapi-generator.tech/docs/generators/go
