### ISSUE TITLE
Develop Resource Management Plan for Public Cluster (1)

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1064]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
List of public cluster services and how they are currently deployed (which nodegroups, memory usage)
Identify solution for limiting service assignment

**Comment by sheridancbio** [comment]
So far I have layed out the topography of the nodes in instance groups and traced the genie-private redis session store helm deployment to instance group "genome-nexus" which is an "unprotected" instance group and I captured the set of docker images running there. (128 unique images, of which 59 are oncokb named). See slack thread : 
https://cbioportal.slack.com/archives/CC3PHP7UN/p1679424707921089
