### ISSUE TITLE
Re-deliver Sophia 100 patient cohort with requested changes

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1069]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Re-deliver 100 patient cohort with below changes

## Technical Description (How are we going to achieve the above)
- [x] Transpose CNA file. (1)

(2)
- [x] Strip row 1 from `data_mutations_extended.txt` (sample id list not needed since sequenced samples list is provided)
- [x] Only deliver `cases_sequenced.txt` and ensure it contains the entire list of sample ids delivered. **- We changed the code to only deliver `cases_sequenced.txt` but it still contains 16,000 samples. Should be debugged.**
- [x] Ask if we need to deliver `cases_sequenced.txt`. If we do need to deliver it, remove metadata from `cases_sequenced.txt` and have it just be one column of sample IDs. **We do not need to deliver it, removed this file from delivery.**
- [x] Drop `data_mutations_manual.txt` from delivery.
- [x] Add consequence column to `data_mutations_manual.txt` **- This column already exists. No need to add.**
- [x] Rename `data_nonsignedout_mutations.txt` to `data_mutations_non_signedout.txt`.
- [x] Drop `AGE_CURRENT` from `data_clinical_patient.txt`.
- [x] Drop `AGE_AT_SEQ_REPORTED_YEARS` from `data_clinical_sample.txt`.
- [x] Filter by PartC Consent Status = Yes **- We clarified this. Conclusion: Don't do any additional consent status filtering as long as we're subsetting from the AstraZeneca cohort**

(3)
- [x] Remove duplicate fields in MAF - for `data_mutations_extended`. (Is one column from CVR and one from GN?). Duplicate fields:

      2 AMINO_ACID_CHANGE - both empty
      2 CDNA_CHANGE - both empty
      2 TRANSCRIPT - both empty
      3 COMMENTS - only 'COMMENTS' has data. Other 2 do not

- [x] Remove duplicate columns in `data_nonsignedout_mutations.txt`: 

      2 AMINO_ACID_CHANGE - no differences
      2 CDNA_CHANGE - no differences
      2 TRANSCRIPT - no differences
      2 COMMENTS - both empty

Note: we removed duplicate columns but in the case of the 'COMMENTS' field, we decided to keep the only version of the column that had data: all uppercase 'COMMENTS'. The `data_nonsignedout_mutations.txt` file does not contain this column so it no longer contains this field in the data.  `data_mutations_extended.txt` contains only this version of the column and the other two were removed.

- [x] Remove COMMENTS column from both MAF files
- [x] Remove gene panels that aren't used
We checked this with: cut -f 2,3,4 data_gene_matrix.txt | sort | uniq

**Comment by callachennault** [comment]
`head -2 data_mutations_extended.txt | tail -1 | tr [:lower:] [:upper:] | tr '\t' '\n' | sort | uniq -c | sort -n
`

**Comment by callachennault** [comment]
```
filenames_to_deliver[data_clinical_patient.txt]+=1
filenames_to_deliver[data_clinical_sample.txt]+=1
filenames_to_deliver[data_CNA.txt]+=1
filenames_to_deliver[data_gene_matrix.txt]+=1
filenames_to_deliver[data_mutations_extended.txt]+=1
filenames_to_deliver[data_mutations_non_signedout.txt]+=1
filenames_to_deliver[data_sv.txt]+=1
filenames_to_deliver[sophia_mskimpact_data_cna_hg19.seg]+=1
```

**Comment by callachennault** [comment]
```
awk '$1!=$2 {print $1,"=",$2}' amino_acid_change_nonsignedout.txt
Amino_Acid_Change = amino_acid_change
```

**Comment by callachennault** [comment]
This command gave us any samples in only one of the two files:
sort sample_list.txt samples_from_sv.txt | uniq -u

This command gave us samples in the second file that aren't in the first:
grep -v -f sample_list.txt samples_from_sv.txt 
grep -v -f samples_from_sv.txt sample_list.txt
