### ISSUE TITLE
Finalize Documentation for Debug Procedure

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1081]

**Comment by callachennault** [comment]
https://mskconfluence.mskcc.org/display/CDSI/Debugging+the+DMP+Pipeline
https://docs.google.com/document/d/1idtrAs6POua9DpSQyRVe7pZxLlm1_fycqn7vgf91cNo/edit?pli=1

Still some TODOs in the Confluence page. Add in contacts section as well
