### ISSUE TITLE
Resolve/Implement Metadata Ambiguity

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1096]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Can determine datatypes for attributes being pulled

**Comment by sheridancbio** [comment]
Approach outlined with Andrew:
- for records of fields defined in the template - we know number v. string for these, so we can code a selection processing a "pure" template.
- for adapted templates, the metadata dictionary (standard library) has permissible value sets. We can attempt to infer numeric v. string values based on the set of permissible values of the field
