### ISSUE TITLE
Deploy Hg38 Portal 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1100]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Double check if publicly accessible or just internally accessible 
Publicly accessible portal (h38) that hosts public hg38 data - (beta.cbioportal.org, beta.cbioportal.mskcc.org)

- [x] build an importer for cgds_hg1938
- [x] create a script for importing into cgds_hg1938 (similar to import-hgnc)
- [x] coordinate with Rob the trigger tool
- [x] point beta.cbioportal.mskcc.org to cgds_hg1938 db (I can help with this)

**Comment by mandawilson** [comment]
- [x] cmo-pipelines PR: https://github.com/knowledgesystems/cmo-pipelines/pull/1046
- [x] pipelines PR: https://github.com/knowledgesystems/pipelines/pull/458
- [x] pipelines-configuration PR: https://github.mskcc.org/knowledgesystems/pipelines-configuration/pull/11

**Comment by mandawilson** [comment]
- [ ] Fix repo build failure: 

https://app.circleci.com/pipelines/github/knowledgesystems/pipelines/25/workflows/5c6a1e5a-663a-42c9-b28d-9aa1cd963fc8/jobs/26

[ERROR] Failed to execute goal on project darwin: Could not resolve dependencies for project org.mskcc.cmo.ks.darwin:darwin:jar:0.1.0: Could not transfer artifact com.querydsl:querydsl-codegen:jar:4.1.1 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/com/querydsl/querydsl-codegen/4.1.1/querydsl-codegen-4.1.1.jar: Connection reset -> [Help 1]

This probably isn't available anymore in maven.

**Comment by callachennault** [comment]
cmo-pipelines persistence functions fix PR: https://github.com/knowledgesystems/cmo-pipelines/pull/1047
