### ISSUE TITLE
Migrate to V2 Account 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1141]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
(This will turn into multiple cards -- coordinate with Gaofei/Kiran about migrating to the V2 account)
Potentially involves the following:
- [x] migrating knowledgesystems importer node
- [x] migrating RDS node
- [ ] validating deployments (?) (Gaofei probably already migrated these) 
- [ ] DNS switchover
- [ ] Potentially move public importer to cluster

**Comment by sheridancbio** [comment]
cataloged ec2 instances and indicated which need our attention
next:
- [ ] catalog rds nodes
- [ ] catalog other assets (snapshots / glacier / ...)
