### ISSUE TITLE
cmo-access is being updated and imported automatically

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1154]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
1. there exists a accessible dataset which is kept up to date (by Dremio) containing the clinical and timeline event info for all cmo-access research and related clinical samples
2. on at least a daily frequency, the cmo-access clinical data from Dremio is being merged and pushed into the cmo-access data repository
3. either Ronak is able to trigger the import of the cmo-access study (mixed_cmo_msk_access_research_dremio_dev) at his discretion, or we have set up a periodic import that meets his requirements

**Comment by sheridancbio** [comment]
Dremio network issue (firewall port) was resolved today by the network security team
