### ISSUE TITLE
Missing Clinical Data for AZ Sample 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1163]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
P-0000106-T01-IM3 recovers clinical data or explained why no clinical data exists

**Comment by callachennault** [comment]
Reached out to CVR team 9/20 and sample was added back into system. As of 9/21 the sample is again present in msk_solid_heme and will be propagated to AZ cohort on 9/25 delivery
