### ISSUE TITLE
Multiple Repo Support

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1168]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
- [x] Airflow Server syncs DAGs managed by multiple teams - DAG repo with submodules (?)
- [x] Document where repos will be

**Comment by callachennault** [comment]
https://github.com/knowledgesystems/cdsi-airflow-dags

**Comment by callachennault** [comment]
Documentation:
- https://mskconfluence.mskcc.org/display/CDSI/Airflow+Dev+Ops#AirflowDevOps-Gitsync
- https://github.com/knowledgesystems/cdsi-airflow-dags#readme
