### ISSUE TITLE
Hackathon

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1178]
### For mysql8.0 compatibility hacking
- [x] install mysql8.0 on a test rds node [hackathon preparation]
- [x] dump data and schema (separately) for current msk portal database [hackathon preparation]
- [x] install schema and note / explore / address any errors/failures
- [x] install data and note / explore / address any errors/failures
- [x] spin up and connect a backend pod which connects to the test database
- [x] test all cBioPortal functionality - note errors/failures
- [x] determine what usage we make of non-ascii characters in our database (if any)
- [x] plan next steps and document overall findings and proposed strategy

**Comment by sheridancbio** [comment]
post-hackathon tasks
- [x] dump database again and compare to insure no data was lost on import
- [x] capture the non-ascii character cases for later review/analysis
- [x] delete rds node, node group, ingress record, dns record
