### ISSUE TITLE
Duplicate variants in MSK_Sophia_LungPts_cBio_mutations_extended - 7-27-23.txt

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#1214]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Understand why duplicates got into MAF.  Update pipeline to remove duplicates from delivered MAF.

- [x] Fix bug checking for duplicates in CMO pipelines code
- [x] Reach out to CVR about duplicate variants being provided for gene aliases
- [x] Add remove-duplicate-maf-variants.py script to AZ generation and Sophia cohort generation scripts

## Technical Description (How are we going to achieve the above)
Sophia claims there are 2556 duplicate variants in mutations extended.  These 2213 are identified by unix sort/uniq

sort -k 1,1 -k 5,5 -k 6,6 -k 7,7 < ~/tmp/sophia-lung-cohort-maf.txt > ~/tmp/sophia-lung-cohort-maf-sorted.txt
uniq -d ~/tmp/sophia-lung-cohort-maf-sorted.txt > ~/tmp/sophia-lung-cohort-maf-duplicates.txt

(sophia-lung-cohort-maf.txt is renamed/copy of MSK_Sophia_LungPts_cBio_mutations_extended - 7-27-23.txt)

[sophia-lung-cohort-maf-duplicates.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMGdPQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9a570ce6b058a2f98547add1d2fdb42a8f3b8102/sophia-lung-cohort-maf-duplicates.txt)

**Comment by callachennault** [comment]
https://github.com/knowledgesystems/cmo-pipelines/pull/1099
