### ISSUE TITLE
Resolve Datadog Warnings on Dev/Prod Machine

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1227]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Timeboxed attempt to remove logging warnings regarding datadog - ~1 day 
- [ ] Warning messages that appear in logs & VSCode connection no longer appears

**Comment by jamesqo** [comment]
It also appears that it is hooking into the NCI pipeline somehow, eg. the debug log messages are getting flooded during a test run: https://gist.github.com/jamesqo/f3b47140a53d444f4a77221930e359c9
