### ISSUE TITLE
Downsize RDS Node 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1228]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
RDS Node boosed to 12xlarge for CDM Release - downsize back to 2/4xlarge

**Comment by sheridancbio** [comment]
Downsized to db.r5.2xlarge instance. This has 64GB of RAM - half of what we have on pipelines3. In theory, there may have been occasional times when the mysqld obtained more than half of the pipelines3 RAM for a particularly difficult query, so possibly this will need to be increased to a 4xlarge node with 128GB of RAM - but let's hope not. 64GB of RAM should be adequate .. especially if people are performing tests on their laptops with 64GB of RAM for running both the mysqld, the cbioportal backend deployment, and a browser app running the frontend.

The new instance is in the same subset as pipelines3.

**Comment by sheridancbio** [comment]
All importers now refer to "mskdb.cbioportal.aws.mskcc.org" rather than an explicit amazon rds endpoint, so no restarting of importers was required. Also all config maps (msk, sclc, internal) refer to the DNS name as well.
