### ISSUE TITLE
Importers/Fetchers Java21 + Core Repo in Prod 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1229]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
- [x] Coordinate migration with Genome Nexus Team
- [ ] Switch the production and dev? hosts (pipeline3/knowledgesystems-importer) to a Java21 jvm
- [ ] Build and deploy importers consistent with a recent version of cbioportal-core
- [ ] Test imports

**Comment by sheridancbio** [comment]
the new cbioportal-core repository is located here:
https://github.com/cBioPortal/cbioportal-core
