### ISSUE TITLE
Support ACCESS-HEME gene panel

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#1233]
- [ ] Follow up with Aijaz and confirm delivery method
- [ ] If needed, update to include new "standalone" cohort that gets merged in 
- [ ] Find and adjust references to P/SID pattern matching in cmo-pipelines 

Per Aijaz, the panel will be release within the next month.  Below is the gene list, we will need to get additional metadata for the cBioPortal file from Aijaz.  We should give external collaborations (AZ, Sophia) a heads up before this goes into production.

ABL1
CD79A
H2AC6
MYC
SETBP1
AKT1
CD79B
HRAS
MYD88
SF3B1
ARID1A
CD83
ID3
NCOA3
SGK1
ASXL1
CDKN2A
IDH1
NF1
SMC1A
ASXL2
CEBPA
IDH2
NOTCH1
SMC3
ATM
CREBBP
IGLL5
NOTCH2
SOCS1
B2M
CSF3R
IKZF1
NPM1
SPEN
BACH2
CXCR4
IRF4
NRAS
SPRED2
BCL2
DMD
JAK1
NT5C2
SRSF2
BCL6
DNMT3A
JAK2
PAX5
SRY
BCOR
DTX1
JAK3
PHF6
ST6GAL1
BCORL1
DUSP2
KDM6A
PIM1
STAG2
BIRC3
EP300
KIT
PLCG2
STAT6
BRAF
ETS1
KMT2A
PML
TCL1A
BTG2
ETV6
KMT2D
POU2AF1
TET2
BTK
EZH2
KRAS
PRDM1
TNFAIP3
CALR
FLT3
LRMP
PTEN
TNFRSF14
CARD11
FOXO1
LTB
PTPN11
TP53
CBL
GATA1
MAP2K1
RAD21
U2AF1
CBLB
GATA2
MEF2B
RHOA
UBE2J1
CCND1
GNA13
MET
RHOH
WT1
CD58
GNAS
MPL
RUNX1
XPO1
CD74
GRHPR
MS4A1
SERPINA9
ZRSR2

**Comment by averyniceday** [comment]
Confirmed introduction of new endpoints from Mihir -- waiting for followup on which datatypes will be included in the endpoint (e.g. support gene panel file creation for SV, CNA, etc.)

Have begun making changes in the cvr codebase - using placeholder endpoint names. 
Remianing tasks 
- [ ] testing (dev server?)
- [ ] evaluate/introduce redcap project inclusion
- [ ] add to overall merge
