### ISSUE TITLE
Update Gene Panels & Deliver to Sophia

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1282]
## Client (Who is making the request)
Curation
## Issue/Deliverable
Gene Panel has updates - need to update in DB potentially. Check if studies need to be re-imported. 
- [x] Deliver and inform Sophia Genetics about gene panel updates - Done by Calla 4/26/24
- [x] Discuss with curation - where do we store gene panels? Where should we centrally store gene panels? Consider s3
- [x] Update gene panels in msk-impact repo (include ACCESS146 which is in AZ-repo rn)
- [x] Re-import IMPACT-HEME-HS panel to the gdac database and studies that use this panel

**Comment by callachennault** [comment]
Updated panels uploaded to shared drive smb://upensmis2/MSKSophia and sophia repo https://github.mskcc.org/knowledgesystems/sophia-data on 4/26

**Comment by callachennault** [comment]
public gene panels stored here: https://github.com/cBioPortal/datahub/tree/master/reference_data/gene_panels
private panels stored ad-hoc in msk-impact, need centralized repo

**Comment by callachennault** [comment]
Gene panel updates: https://github.mskcc.org/cdsi/msk-impact/pull/1

**Comment by callachennault** [comment]
Removing public gene panels: https://github.mskcc.org/cdsi/msk-impact/pull/2
