### ISSUE TITLE
Complete Databricks Training Course

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1296]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
- [ ] Rob
- [x] Avery
- [x] Calla
- [x] James
- [ ] Manda

**Comment by callachennault** [comment]
https://mskconfluence.mskcc.org/pages/viewpage.action?spaceKey=MODE&title=Onboarding+to+MODE
