### ISSUE TITLE
Deploy Sample Coverage/CT Code

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1303]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
- [ ] sample coverage values populated for CT (in archer)
- [ ] new fields added to checked in GH files
- [ ] new fields added to redcap

**Comment by callachennault** [comment]
https://github.com/knowledgesystems/cmo-pipelines/pull/1177
https://github.com/knowledgesystems/cmo-pipelines/pull/1189
