### ISSUE TITLE
data discrepancies corrected in graphite databases

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#1327]

**Comment by sheridancbio** [comment]
Comparisons of api output for the most-recent versions of oncotree in topbraid (v. graphite) show some differences. Adjust graphite data to match production versions.

**Comment by mandawilson** [comment]
All versions now match with the TopBraid & Graphite backends except for oncotree_development.  They also match what is described on the News page.  There are a few small differences in oncotree_development which I described to Ritika and I am waiting for feedback from her.
