### ISSUE TITLE
Investigate missing IMPACT patient/sample data

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#1331]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Understand why and possible recover 116 patients whose data has failed to be imported after requeue.  The data was requeued in the afternoon of June 6 and should have been available on June 7.

- Per Mihir - the samples have not been consumed on the CVR side.

## Technical Description (How are we going to achieve the above)
The following 116 patient data is not in the cBioPortal after a requeue by the CVR team.  Are these VIP patients or is something else preventing them from being imported?

P-0003288, P-0006119, P-0011588, P-0013827, P-0014773, P-0014831, P-0017283, P-0019219, P-0024116, P-0025776, P-0026507, P-0028566, P-0031037, P-0031876, P-0032217, P-0033801, P-0035828, P-0036404, P-0036528, P-0038284, P-0038988, P-0039073, P-0039577, P-0044079, P-0045591, P-0045745, P-0046691, P-0047440, P-0047569, P-0047793, P-0047825, P-0048832, P-0048863, P-0051371, P-0053750, P-0053775, P-0056206, P-0056207, P-0060664, P-0061350, P-0061576, P-0062708, P-0062756, P-0065440, P-0066643, P-0066647, P-0066648, P-0066650, P-0066652, P-0066653, P-0066981, P-0069270, P-0070493, P-0070731, P-0070767, P-0070823, P-0071232, P-0071367, P-0071467, P-0071635, P-0071786, P-0071886, P-0072032, P-0072501, P-0072547, P-0074271, P-0074484, P-0074698, P-0075138, P-0075188, P-0076386, P-0076972, P-0077049, P-0077449, P-0077571, P-0077646, P-0077811, P-0078146, P-0078740, P-0078848, P-0079000, P-0079001, P-0079153, P-0079174, P-0079249, P-0079257, P-0079430, P-0079469, P-0079680, P-0080228, P-0080661, P-0081126, P-0081140, P-0081159, P-0081202, P-0081392, P-0081401, P-0081456, P-0082639, P-0082801, P-0082837, P-0082880, P-0083034, P-0083257, P-0083300, P-0083460, P-0083476, P-0085027, P-0085158, P-0085761, P-0086773, P-0090694, P-0090837, P-0092694, P-0093156, P-0095228

**Comment by averyniceday** [comment]
Need more information from Mihir about specific samples -- 

Using a grep across a couple random points in git history show there are some patients with samples in the history that are not longer present -- trying to requeue results in failure to requeue/not in masterlist. Potentially removed? 

Couple cases where couldn't find an exact sample, ran a check in DDP - there are also cases where the patient is not in DDP. Not sure if this is a valid check

**Comment by averyniceday** [comment]
Verify is these in our data -- (if possible, when they were introduced, or at least they were introduced at the same time)
P-0031037-T03-IM6
P-0038284-T01-IM6
P-0033801-T03-IM6
P-0031876-T03-IM6
P-0045591-T02-IM6
P-0047825-T01-IM6
P-0047793-T01-IM6
P-0031037-T04-IM6
P-0047793-T02-IM6
P-0061350-T01-IM7
P-0061576-T01-IM7
P-0047793-T03-IM7
P-0031037-T05-IM7
P-0071232-T01-IM7
P-0077571-T01-IM7

**Comment by averyniceday** [comment]
Find a handful of samples associated with original patient ids -- try to requeue
