### ISSUE TITLE
Investigate "MUTATED" annotation for multiple records in MSK-IMPACT data_mutations_extended.txt (as of 6/21/2024)

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#1344]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
As reported by Enrico Mioso:

> I was working on one case for the breast molecular tumor board and I’ve found the following issue (and Walid suggested me to reach to you):
> Pt P-0103770 has IMPACT on 2 samples.
> Both samples have the TP53 p.R213* but in cbioportal in one case it is properly called  while in the other is called TP53 MUTATED
> This is not incongruence is not observed in CVR nor in the report.
> If I look a the maf file from github I've noticed something being off. The Entrez ID is 0, the NCBI_build is 37 and the is a left shift for Consequence/Variant_Classification.
> Diving in the data_mutations_extended.txt  (v. 2024_06_21)  there are 474 cases with NCBI_build == 37 and 133023 cases with EntrezID == 0.
> I hope this is useful, happy to provide more info

**Comment by averyniceday** [comment]
Reannotating with the example records solved the immediate issue - requeuing overnight and seeing if behavior is different
