### ISSUE TITLE
Test Airflow Stability Across Different Node Group Configurations 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1347]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
- [x] Document which datadog metrics to look at for checking performance of individual dags/scheduler pods
- [x] Propose alternate nodegroup/resrouce configurations
- [x] Run both NCI/CDM DAGs and collect datadog metrics - propose estimated resource usage for each task

**Comment by callachennault** [comment]
Conclusion: r5.xlarge works for now, supporting additional DAGs will require testing wrt CPU usage on current deployment
