### ISSUE TITLE
Check-in/Document Airflow Configurations

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1360]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Enter documentation and configuration files into k8s-knowledge-repo/portal-configuration/confluence. 

User shoudl be able to spin up an airflow server from scratch with similar setup.

**Comment by callachennault** [comment]
https://github.com/knowledgesystems/knowledgesystems-k8s-deployment/pull/216
