### ISSUE TITLE
Test Chris' DAG Updates

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1368]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Test Chris' DAG updates and turn off hpc3 DAGs

**Comment by callachennault** [comment]
https://github.com/clinical-data-mining/dags/pull/19
https://github.com/clinical-data-mining/cdm-cbioportal-etl/pull/82
https://github.com/knowledgesystems/cmo-pipelines/pull/1196
