### ISSUE TITLE
Update Import Users Script to Work with Clickhouse Stack

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1403]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Import Users script is automatically updated to point/sync between green and blue databases when a GENIE import is finished

**Comment by mandawilson** [comment]
We need to be able to switch over, but also synchronize.  We can't just pause user imports.  Maybe:

- [ ] 1) disable user import script

- [x] 2) synchronize databases (users) - maybe just run import users script again - then they get a second email - maybe import but don't send email?  maybe cleaner to just synchronize

- [ ] 3) switch over portal & change tracking table

- [ ] 4) restart import users script

Check with Avery & Calla about Airflow and import users script.
