### ISSUE TITLE
Update Flow Control for Derived Table Script

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#1404]

**Comment by mandawilson** [comment]
Look for table name genetic_alteration_derived.  We can run the create table, and the optimize table.  Not the insert step -- at this point call Rob's new script.

**Comment by mandawilson** [comment]
Another table (generic_assay?) has the same comma separated list.  Even if it doesn't have data problem it might have same memory problem.  We should treat it the same way.

Also script could be improved.  Transform the query instead of hard coding it in script.
