### ISSUE TITLE
create cgds_hgnc database and importer

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#151]
New pipelines database for imports using HGNC gene table:
- [x] clone cgds_gdac as cgds_hgnc
- [x] delete all studies from cgds_hgnc
- [x] wipe out orphan records from mutation_event and cna_event
- [x] take a snapshot at this point ... so that we can return to here if we need to going forward
- [x] insert/update records from HGNC_dump_in_ncbi_format.txt and clear out records not in HGNC_dump_in_ncbi_format.txt - requires new records in genetic_entity to be created
- [x] also load the gene_alias table with previous symbol records
- [x] clean up any "unreferenced GENE genetic entity id records from genetic_entity"
- [x] run the "initialize miRNA genes" script (scripts) XXXXX no, we will not be using miRNA genes/gene-sets
- [x] there are 18 entries in geneset_list??? that refer to negative gene id number .. make sure they end up "correct"
- [x] drop all gene sets from database
- [x] set up permissions
- [x] delete users and authorities?
- [x] relocate database onto dashi-dev server
------------------------------------
- [x] build and deliver a new importer jar, pointed at the new database
- [x] pulling repositories? which fetches need to happen? .. this runs entirely as a local machine / .jar from laptop?
- [x] import script / crontab entry for running the import
- [x] either a new column in the importer configuration spreadsheet or some kind of trigger file / script they can run
------------------------------------
- [x] decide / comment on how the datahub (and future) source repositories will be updated before import
- [x] check in importer.properties, log4j.properties (pipelines-configuration)
- [x] polish import script for hgnc-portal
- [x] check in import script for hgnc-portal (import-scripts)
- [x] standalone? build script for hgnc importer jar (deploy?)
- [x] test imports, set group permissions for importer jar and scripts
- [x] knowledge share locations / use with curators

**Comment by mandawilson** [comment]
Creating the website and importer:

I imported one study into the cgds_hgnc_debug  database on dashi-dev : http://dashi-dev.cbio.mskcc.org:8080/hgnc-debug

To import (on dashi-dev): /data/portal-cron/scripts/import-hgnc.sh

First you have to make sure whatever study you want is here: /data/portal-cron/cbio-portal-data/datahub/

Using this method `git lfs pull -I public/brca_tcga`, explained here: https://github.com/cBioPortal/datahub
