### ISSUE TITLE
Move archived hg repos into S3

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#498]
current location on pipelines:
/data2/portal-cron/cbio-portal-data/dmp/archive-bare/dmp-2020.git.tar.gz

-[ ] Move Headless Clones of HG Repos into S3 Glacier [3 points]

**Comment by averyniceday** [comment]
Meeting scheduled for Monday December 13th to discuss business case for using S3 Glacier with the Cloud Team

**Comment by sheridancbio** [comment]
done.
EC2 node used for compression deleted. all mercurial repos in SCM deleted. Backups still maintained on pipelines server in /data2
Also : dmp-2020 and dmp-2021 complete dumps backed up to S3 in new bucket ... cbioportal-git-data-repo-archive
