### ISSUE TITLE
create parallel msk github repositories for select mercurial data repos

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#500]
Move the data repositories (excluding portal-configuration IF requires more coordination with frontend - `portal-configuration/pipelines-configuration` msk github)
Mercurial sitting with a headless on pipelines for now. 

Dec 1 2021-
Based on discussions with @ritikakundra, we should merged private/impact into a single repos called something like **curation** (not sure the implications of this on preserving history).  Need to pull Ritika into conversation to finalize details.

Do not need to include history
Ritika will send up a spreadsheet with source to destination mappings

**Comment by averyniceday** [comment]
List from curators of repos to migrate

https://docs.google.com/spreadsheets/d/1OeDiaOIPmekZIB3wL1LlsdVFz1baxzw_pkGBk9Pk99o/edit#gid=0

**Comment by sheridancbio** [comment]
summary of work to do:
- [x] archive/delete these repos:
    - [x] dmp
    - [x] foundation
    - [x] genie
    - [x] grail
    - [x] immunotherapy
    - [x] msk-impact
    - [x] rudin_mskcc
    - [x] solit_mskcc
    - [x] bic-mouse (Manda says please delete)
- [x] migrate these repositories into msk-github:
    - [x] automation_testing
    - [x] cbio-portal-data
    - [x] impact
    - [x] portal-configuration (destination existing MSK GITHUB portal-configuration)
    - [x] private
    - [x] shah-lab
- [x] confer with someone, then migrate or del:
    - [x] brlo_tcga
    - [x] crdb_pdx
    - [x] gdac_provisional_tcga
    - [x] hgadmin (probably ignore)
    - [x] levine_mskcc
    - [x] pancan_tcga
    - [x] redcap-snapshot (maybe dropping soon)
    - [x] session-service-configuration
    - [x] ucec_tcga
    - [x] yale_brain_tumor
- [x] figure these out:
    - [x] bic-mskcc

**Comment by sheridancbio** [comment]
the plan for bic-mskcc repo now is:
- everything under /pi or /ci paths are related to argos/Tim and will migrate into the ARGOS mskcc github repo when Tim is ready to switchover.
- everything else will go into a legacy "bic-mskcc" data repository in the mskcc github.
The importers will get these two new locations as data sources and when they are both up and running we will drop the mercurial data source.

**Comment by sheridancbio** [comment]
for "confer with someone" repos, I have examined the last update date:
brlo_tcga : Tue Jul 22 10:40:30 2014 -0400 (ciriello <ciriello@cbio.mskcc.org>)
crdb_pdx : Sun Feb 27 20:19:13 2022 -0500 (cBio Portal Importer)
gdac_provisional_tcga : Mon Jul 16 14:46:41 2018 -0400 (ramya)
hgadmin : &lt;none>
levine_mskcc : Thu Dec 11 10:39:56 2014 -0500 (n1zea144)
pancan_tcga : Tue May 29 16:23:25 2018 -0400 (Angelica Ochoa <ochoaa@mskcc.org>)
redcap-snapshot : Tue Feb 22 19:03:58 2022 -0500 (cBio Portal Importer)
session-service-configuration : Mon Nov 13 14:59:26 2017 -0500 (Manda Wilson <wilson@cbio.mskcc.org>)
ucec_tcga : Thu Mar 14 22:27:12 2013 -0400 (Jianjiong Gao <jianjiong.gao@gmail.com>)
yale_brain_tumor : Tue Sep 15 19:49:01 2015 -0400 (JJ Gao <jgao@cbio.mskcc.org>)

To see whether these need to be maintained, we should see which studies fall under the paths present in them .. and either remove them from the importer configuration spreadsheet, or carry them over (especially if the study is currently imported).

**Comment by sheridancbio** [comment]
brlo_tcga .. not organized into recognizable studies for import. Also old. -- archive and delete (m->Giovanni)
crdb_pdx .. in use by import-pdx-data.sh ... convert to mskgithub
gdac_provisional_tcga .. none of the directory paths here are in importer_config -- archive and delete
hgadmin .. this is a meta repo for mercurial admin. Back it up, but leave it alone.
levine_mskcc .. has importable studies. convert to mskcc github repo
pancan_tcga .. has importable studies. convert to mskcc github repo
redcap-snapshot .. planned for retirement, but in active use now. convert to mskcc github repo
session-service-configuration .. not sure - but small and has build scripts/props. convert to mskcc github repo
ucec_tcga .. no importable studies. Seems to be source data .. possibly relocated into datahub. archive/delete
yale_brain_tumor .. no importable studies. Seems to be source data. archive/delete .. mention to JJ (+ucec)
