### ISSUE TITLE
try to improve backend performance of Gene Panel data fetch on mskimpact study view

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#502]
see network tab during study load

Loading of MSK-IMPACT Study View network tab:

![image (2)](https://user-images.githubusercontent.com/366003/109315735-d7ccbf00-7818-11eb-8054-0c28efb4868e.png)

JProfiler capture of gene-panel-data fetching:

![image](https://user-images.githubusercontent.com/366003/109315515-9f2ce580-7818-11eb-9049-ad6aa72851a2.png)

**Comment by jjgao** [comment]
@sheridancbio @averyniceday: Karthik also worked on the gene panel performance and has submitted a pull request: https://github.com/cBioPortal/cbioportal/pull/8423
