### ISSUE TITLE
update properties files for cache fix

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#508]
- new build by Ino coming .. properties files must be in place if the fix code is to be merged in

https://github.com/cBioPortal/cbioportal/pull/8408

**Comment by averyniceday** [comment]
Talked to Ino about this, he's approved the PR and I believe it's deployed to beta for testing. 

It should be deployed with the next release. Will move to done once PR is merged and is deployed to MSK portal.
