### ISSUE TITLE
document deployment / maintenance process / procedures 

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#514]
complete documentation of deployment steps
check in yaml configuration files and any scripts we have developed or used
- [x] updated doit.sh (including tags center/owner..)
- [x] add a link into the readme to the cost center tag location
- [x] check-in new "values.yaml" needed for ebs provisioner
- [x] check config maps into the mercurial repo (portal-configuration)
- [x] check deployments / services / ingress yaml files into knowledgesystems-k8s-deployments git repo [scan for hardcoded creds.]
complete a schematic of the cluster components / dataflows ... see :https://app.lucidchart.com/lucidchart/a14b5d41-4674-4625-b93e-5a5fe7a7854f/edit?page=0_0#

end goal: have something ready to drive the deployment into the production account

note: choose scripting steps or console steps as appropriate
note: the github.cbioportal.mskcc.org "portal-configuration" repo is limited to cluster initialization/preparation.

**Comment by averyniceday** [comment]
For reference, I believe the ending state of this is we have docs and stuff checked into the msk github eks and k8s eks directory. I think @sheridancbio wanted to add some additional info. 

The rest of it is more team discussion about how this can be managed going forward (e.g who is manging it, production vs dev) which I think may become clearer and more relevant as we start shifting to prod.

**Comment by averyniceday** [comment]
**Cluster-only related docs here**
https://github.mskcc.org/knowledgesystems/portal-configuration/tree/master/eks-cluster

**eks-cluster yaml files** 
Checked into k8s-knowledgesystems repo

**helm commands**
This is general portal setup and can be done in the environment just following usual deployment docs
