### ISSUE TITLE
performance examination of imports from pipelines into AWS eks

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#528]

**Comment by averyniceday** [comment]
Attempting to build an importer from pipelines to the eks cluster

**Comment by averyniceday** [comment]
importer jar sitting in pipelines cbioportal_importer home directory
`/home/cbioportal_importer/eks-importer.jar`

Using a quickimport.sh script to import based on hot-deploy column.

For reference the eks db has three users:
```
admin (self-explanatory) 
cgds_user (portal)
cgds_admin (importing)
```

I will create a file in my home directory on pipelines in case people want the passwords to build their own importers. DB string is taken from the deployed config map (can also be taken from the aws console I believe)

**Comment by averyniceday** [comment]
Imported our test study which completed without issues. 
Started another import of mskimpact at 3:15. Logs are in eks-importer.log - can get an idea of when job ends from there
