### ISSUE TITLE
set up redis persistence caching for eks cluster deployments

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#530]

**Comment by averyniceday** [comment]
!!! 

```
helm install cbioportal-persistence-redis bitnami/redis --set master.nodeSelector."eks\.amazonaws\.com/nodegroup"=essential-medium
```

and yes, if we don't set the nodegroup the portal doesn't have enough memory to startup if scheduled onto same node!

**Comment by averyniceday** [comment]
added new cname recrod for eks-session-service.cbioportal.org in google domains + updated ingress and deployment yamls
