### ISSUE TITLE
Change error message when user does not have access to study.

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#531]
Can we "polish" the error message returned when a user does not have access to a study (see below). Maybe something like:

"The study you are trying to access does not exist, or you do not have access to the study".   This may require some front-end help.

![image.png](https://images.zenhubusercontent.com/570fd610bf93871ccd99739b/3e6acc48-8e6f-454d-9db3-a60add8d4edb)

**Comment by mandawilson** [comment]
The error message is occurring when the front end calls a backend API endpoint with data: "[]".  The front end then displays the backend error message.

Really the frontend shouldn't call that endpoint if it has no valid studies in the list.  I am guessing it has already validated the study, found it invalid, and filtered it.

**Comment by mandawilson** [comment]
I created an issue for the frontend: https://github.com/cBioPortal/cbioportal/issues/8500
