### ISSUE TITLE
document our Keycloak management SOP

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#543]
capture our security / safety measures
separation of msk users and outside collaborators [insulation by realms]
keycloak administrators [the possible roles and which users will have those rights / roles ]
update schedule for keycloak patches / security fixes
offline token use [for data access tokens in cbioportal]
cmo pipeline keycloak adjustment scripts [new studies / user authority updates]

** there may be a good template available through Joanne

[InternalAuditSystemDocumentation_2.pdf](https://github.com/knowledgesystems/pipelines-scrum/files/6392947/InternalAuditSystemDocumentation_2.pdf)

**Comment by averyniceday** [comment]
https://docs.google.com/document/d/1B9QjW4QIBGx61cS4IxTKP0axu9DfUyEwlFbEcujm9rs/edit?usp=sharing
