### ISSUE TITLE
determine users with access to genie-private portal

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#547]
we can accomplish this from the keycloak database. Include both synapse and google ids.

Report to Ritika

**Comment by mandawilson** [comment]
The users with access to the genie-private portal are listed on pipelines in this file: /data/manda/tmp-genie/genie-private_users_with_access.txt .  When NULL is in the FIRST_NAME, LAST_NAME, and EMAIL columns the user has never logged in.  When you see a number in the USERNAME field that is the Synapse/Sage account id.  @rob thinks we were given a file by Tom that lists the users in Synapse that should be given access and it might link these account ids to emails.
