### ISSUE TITLE
investigate / debug performance of the redis server on pipelines

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#548]
restarts seem to fix the msk-tomcat when it is stalling / failing / reporting connection errors to redis
we increased the logging level of the pipelines redis server -- so examine the logs for clues
review the messages in the msk-tomcat logs related to redis

if possible, make adjustments to the redis server to make it more reliable -- possibly "tune" the redisson parameters on msk-tomcat

Status 500 captured by Niki:
![image](https://user-images.githubusercontent.com/366003/116425423-483f8e80-a810-11eb-98ab-d37d08fe7534.png)

**Comment by mandawilson** [comment]
On `pipelines` redis is here: `/srv/data/redis/redis-stable/`

**Comment by mandawilson** [comment]
On `dashi` you can see an `OutOfMemory` error 3 minutes after the timeout:

```
Mon Apr 26 23:58:53 EDT 2021 WARN: Establishing SSL connection without server's identity verification is not recommended. According to MySQL 5.5.45+, 5.6.26+ and 5.7.6+ requirements SSL connection must be established by default if explicit option isn't set. For compliance with existing applications not using SSL the verifyServerCertificate property is set to 'false'. You need either to explicitly disable SSL by setting useSSL=false, or set useSSL=true and provide truststore for server certificate verification.
[redisson-netty-1-25] WARN org.redisson.client.handler.CommandDecoder - response has been skipped due to timeout! channel: [id: 0xb10572a0, L:/140.163.153.65:60932 - R:pipelines.cbioportal.mskcc.org/140.163.153.185:6379], command: (HGETALL), params: [redisson:tomcat_session:0B7909711F9525443E4BE8090C4D72D7.ajp13dashi-two5], result: {session:thisAccessedTime=1619496075637, session:creationTime=1619496075635, session:isValid=true, session:isNew=false, SPRING_SECURITY_SAVED_REQUEST=DefaultSavedRequest[https://cbioportal.mskcc.org/], session:maxInactiveInterval=43200, session:lastAccessedTime=1619496075635}
27-Apr-2021 00:02:35.562 SEVERE [ajp-nio-58009-exec-9] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [api] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded] with root cause
 java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.lang.reflect.Constructor.copy(Constructor.java:149)
        at java.lang.reflect.ReflectAccess.copyConstructor(ReflectAccess.java:148)
        at sun.reflect.ReflectionFactory.copyConstructor(ReflectionFactory.java:330)
        at java.lang.Class.getConstructor0(Class.java:3079)
```

**Comment by mandawilson** [comment]
Lots of `OutOfMemoryError` errors on both machines: `grep -B1 java.lang.OutOfMemoryError catalina.out | grep SEVERE`

**Comment by mandawilson** [comment]
Maybe monitor the connection to redis on pipelines from dashi? 
Maybe use net stat to see the total # of open connections to redis server?

URL: `redis://pipelines.cbioportal.mskcc.org:6379`

**Comment by mandawilson** [comment]
Performance logs (cpu, memory) are on `dashi` and `dashi2`: `/srv/www/monitoring/msk-tomcat-monitor/performance/view performance_log.txt`

**Comment by mandawilson** [comment]
Socket timeout set?
Upgrade redission library?

**Comment by mandawilson** [comment]
JProfiler hooks into Tomcat.

**Comment by mandawilson** [comment]
The version of redisson for msk-tomcat on dashi/dashi2 (for the session management): 3.7.4 (redisson-all-3.7.4.jar, redisson-tomcat-8-3.7.4.jar).

Latest is 3.15.4 - maybe test this on dashi-dev and then on dashi?

Example [Redisson Single instance YAML config format](https://github.com/redisson/redisson/wiki/2.-Configuration#262-single-instance-yaml-config-format)

**Comment by sheridancbio** [comment]
a monitor script is watching the redis server responsiveness from both dashi and dashi2.

See the log files (sampling each second) and script in my home directory on these machines (/home/sheridan/redis_server_probe)

**Comment by sheridancbio** [comment]
Today we:
- attempted to adjust the redisson.yaml parameters -- but needed to revert due to errors
- upgraded the version of the redisson client library on dashi and dashi2
- began to probe the memory issues in the tomcat logs

#### problematic update of redisson.yaml parameters
The old default of nettyThreads was believed to be 64 (2 * the java number of cores on the dashi/dashi2 servers). We altered this to 256, and in about a 10 minute time frame there were failures and errors in the logs and visible to users visiting cbioportal.mskcc.org. Log messages were of the form "OutOfMemoryError: unable to create new native thread". It was also not possible to su msk-tomcat at this time "su: cannot set user id: Resource temporarily unavailable", which seems to be a limit on the number of threads the system will allocate to a user. Initially the parameter change also included changes to `timeout` and `retryInterval`, but those changes were reverted and we were still seeing the native thread creation problems. We rolled back all changes until we could figure out what these memory loads were coming from.

#### upgrade of redisson library
An upgrade from redisson-tomcat-8-3.7.4 to redisson-tomcat-8-3.15.4 .. this went smoothly and seemed stable [running ~2 hours now]

#### memory exhaustion issues and ideas
- background : earlier in the week we looked back into the catalina.log history when there were reported slowdowns / needed restarts of tomcat. At first we saw cases where a number of redis "ConnectionTimeout" exceptions were followed by a OutOfMemory : heap space error and needed restart. However, further looking showed cases where ConnectionTimeout errors were not followed by OutOfMemory -- although they did seem to correspond with apparent GC runs when we looked at performance logs here : /srv/www/montoring/msk-tomcat/performance
- we learned that when system lockups happen, thread monitoring in jprofiler also fails. Also, we saw that the JProfiler seems to only see the heap allocation, not the full memory usage (see below)
- during all failures, the independent monitor of connections to the redis server on pipelines showed that the redis server was not misbehaving during the failures/outages
- at "top" monitoring of the msk-tomcat jvm process showed an expected (5-10 GB) of resident memory usage - roughly tracking the specified 10GB heap size limit set with -Xmx. However ... we noticed a surprising virtual memory usage of 30-35GB. After discussion we thought that this memory usage is not being tracked by Jprofiler and is not being contained by the garbage collector. We are unsure what this memory represents, but we did determine (using the java jvm on dashi) that the Runtime reports a Runtime.maxMemory() size of 28GB. This is described as "the maximum amount of memory that the Java virtual machine will attempt to use" and it is in the ballpark of where total process virtual memory reached during run. We are now suspecting that this extra memory is connected to the allocation of stream buffers for nio operations: https://docs.oracle.com/cd/E14447_01/coh.330/coh33ug/niomemorymanager.htm or maybe for stack storage for the numerous threads being forked for the web applications. We may explore settings such as -XX:MaxDirectMemorySize
- after deploying the update to redisson 3.15.4 we realized that we had actually lowered the setting of nettyThreads (because of a new default) from 64 to 32. The running web application seemed to have a lower resting-level of virtual memory (dropping from 36GB to 31GB) It is uncertain if fewer nettyThreads leads to a lower memory footprint.

**Comment by mandawilson** [comment]
The default nettyThreads was previously cores * 2 (so 64) and now is 32.  This might be helping.
