### ISSUE TITLE
create EC2 instance which mirrors current pipeline machine

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#555]
- [x] need appropriate users (cbioportal_importer)
- [x] need clones of codebases / credential files
- [x] need matching system binary tools (java, python, mysql, ...)
- [x] clone needed data repositories (possibly on a persistent volume) for : dmp_importer, cmo_importer, triage_importer [not genie, not public]

**Comment by averyniceday** [comment]
Followed instructions here: 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-basics.html

Then also added sheridan and wanga5 to docker group so we can execute

**Comment by averyniceday** [comment]
I've tested an import from the new machine to the database and that has completed successfully. I had to create a hacked importer to stop it from connecting to Redcap/CDD which we don't have access to yet. There's already a request sent in by Rob for opening up those ports. Once approved we can move to testing the entire run. 

Things left:
- [ ] script for installing dependencies
- [ ] clone mercurial repositories
- [ ] full run test (but this is closer to the other card)

**Comment by sheridancbio** [comment]
This work required making a request to open ports in the MSK firewall for connections coming from the AWS EKS cluster address ranges.
A request was submitted May 10 to allow connection coming from private network addresses:
digits AWS EKS dev cluster subnet A	CIDR 10.1.16.0/25 [range 10.1.16.0 -> 10.1.16.127]	any	http, https, mysql, db2, ssh
digits AWS EKS dev cluster subnet B	CIDR 10.1.16.128/25 [range 10.1.16.128-> 10.1.16.255]	any	http, https, mysql, db2, ssh
digits AWS EKS dev cluster subnet C	CIDR 10.1.17.0/25 [range 10.1.17.0 -> 10.1.17.127]	any	http, https, mysql, db2, ssh
digits AWS EKS prod cluster subnet A	CIDR 10.1.20.0/25 [range 10.1.20.0 -> 10.1.20.127]	any	http, https, mysql, db2, ssh
digits AWS EKS prod cluster subnet B	CIDR 10.1.20.128/25 [range 10.1.20.128 -> 10.1.20.255]	any	http https, mysql, db2, ssh
and going to internal msk network hosts / ports:
pipelines.cbioportal.mskcc.org		22, 80, 443, 3306	ssh, http, https, mysql
ddp.mskcc.org		http, https
ramen.cbio.mskcc.org		22, 80, 443	ssh, http, https
dashi.cbio.mskcc.org		22, 80, 443, 8080, 28080, 58080	ssh, http, https
dashi2.cbio.mskcc.org		22, 80, 443, 8080, 28080, 58080	ssh, http, https
lynx.mskcc.org		9770	http, https
draco.mskcc.org		9775	http, https
plcrdbd2.mskcc.org		1526	oracle database client driver
pidvudb1.mskcc.org		51013	db2 database client driver
github.mskc.org		443	https


Status on May 14:

Request has been acted on by digits, we have tested connections from various points in the source address block ranges for the dev cluster. The 3306 mysql port to pipelines cannot be tested because there is a firewall on the target machine not allowing incoming connections. Also ports 80 and 443 and 8080 on dashi and dashi2 are not deploying services we need currently. Aside from these, only the db2 and oracle ports seem to have not been opened to the dev cluster.

Testing of the prod cluster cannot be done until we are granted authorities to create keypairs for launched ec2 instances.

**Comment by averyniceday** [comment]
**Isolated Testing**

- [ ] import into EKS db
- [ ] redcap pipeline
- [ ] CRDB fetch
- [ ] DDP fetch
- [ ] Darwin fetch
- [ ] CVR fetch
- [ ] local build

**Comment by sheridancbio** [comment]
We believe the darwin fetcher is able to reach the darwin db2 port ... but we are seeing a failure to connect from the db2 driver:
[2021-05-18 19:47:44.272] boot - 23430 ERROR [main] --- AbstractStep: Encountered an error executing step mskimpactTimelineBrainSpineStep in job mskCaisisJob
java.lang.RuntimeException: DB2 SQL Error: SQLCODE=-1060, SQLSTATE=08004, SQLERRMC=DVCBPAPS, DRIVER=4.15.134
	at com.querydsl.sql.SQLQueryFactory$DataSourceProvider.get(SQLQueryFactory.java:47) ~[querydsl-sql-4.0.9.jar!/:?]
	at com.querydsl.sql.SQLQueryFactory$DataSourceProvider.get(SQLQueryFactory.java:34) ~[querydsl-sql-4.0.9.jar!/:?]
	at com.querydsl.sql.AbstractSQLQuery.connection(AbstractSQLQuery.java:660) ~[querydsl-sql-4.0.9.jar!/:?]


We think this may require an adjustment of the firewall, or the incoming host authorization list for the db2 system. We will need to reach out to darwin for them to allow incoming connects from any ip address in the ranges possible for the eks development and production clusters.

**Comment by sheridancbio** [comment]
#### remaining tasks
- [ ] clone cbio-portal-data and move in (or clone in) the other repositories needed
- [ ] figure out how to run pipelines imports on production machines while having a concurrent process running on eks pipelines (fetching cvr / requeuing) - also avoid "using" the commits that happed during the production run into the data repositories while running the eks pipeline script.
- [ ] automation environment script .. a clean / maintainable and minimally disruptive approach for setting up a new pipelines server while using our checked in scripts
- [ ] add mercurial tool version 4.0 download .rpm module and installation into the setup system script
