### ISSUE TITLE
Successful Full Run of Nightly Import Processes 

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#557]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
We need a full run of the overnight dmp processes before deploying to prod. This will be used to help fine-tune any small remaining issues. 

## Technical Description (How are we going to achieve the above)
- run a full run of the fetch-and-import-dmp script w/ repo commits turned off
- any big issues should be put into another card

## Potential Issues
- Missing mail server
- Firewall Issues
### Technical Requirements
- Open SMTP Port on pipelines
### Outside People/Teams
Joanne (alter existing mail server)
DIGITS (new mail server) 
## Changes

Done condition:

Full run, results are captured - fine tune small fixes

aside from pushes to the data repositories (to avoid conflicts with the pipelines machine which is still running) the full nightly fetch / import processes (including redcap Import/Export) are running on the EKS cluster node which was set up.

updated importers/fetchers can also be built on this machine when needed (build-importer-jars)

----------

during testing, the consumption of fetched samples will continue on pipelines as normal. The EKS system (during test) will not consume any samples and when we want to test / verify testing processes we will manually requeue the nightly fetched samples before the EKS run, and then manually consume the samples after the EKS run is complete.

**Comment by averyniceday** [comment]
- [ ] test CVR fetch
- [ ] test Darwin fetch
- [ ] import time comparison

**Comment by averyniceday** [comment]
blocked until darwin provided dev db pw

**Comment by mandawilson** [comment]
Firewall is not open between dev node and dev darwin server because we didn't know there was a dev darwin server (so we never asked them to open the ports).  Rob sent an email asking them to open the ports, and to close the ports between our dev node and the production darwin server.

**Comment by averyniceday** [comment]
This card has been updated to performance test different db setups (RDS node, size, local, etc.) since a full run is too long.
