### ISSUE TITLE
move pipelines-configuration repository into msk enterprise github

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#558]
Before importing it :
- [x] make sure to define the limits of who will have access to this repository - NEW REPOSITORY
- [ ] capture that list in README.md (so we remember)
- [ ] go through the repo and remove any credentials which should have more restricted access than represented by the access list
- [ ] update scripts to pull from new location if necessary (but probably not)
- [x] notify people who use it

**Comment by averyniceday** [comment]
git repo located here
`/srv/data/local/pipelines-git/pipelines-configuration.git`

Will decommission after a couple days pass from notification, would like to have someone look over my shoulder when I do this.
