### ISSUE TITLE
GENIE Project Managers have Keycloak admin access

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#570]
GENIE project managers would like to have admin access to CRUD GENIE users access to GENIE portals.  They have already been trained by Ritika.  Please provide the following users admin access within GENIE realms only:

yekaterina.khotskaya@aacr.org
shawn.sweeney@aacr.org

-- support batch import of user lists if possible

**Comment by mandawilson** [comment]
keycloak.cbioportal.org

**Comment by mandawilson** [comment]
I tested this first with my gmail account and then Ritika tested with hers. Then Ritika logged in as an admin and did the following:

In the `genie-private` realm she searched for the users and selected their gmail accounts.  She then went to the `Role Mappings` tab for each user.  In the `Client Roles` drop down she selected `realm-management` and then added `manage-users` and `view-users` from the `Available Roles` section to the `Assigned Roles` section.  

Users should then go to https://keycloak.cbioportal.org/auth/admin/genie-private/console to do CRUD user operations in genie-private.

Ritika is going to update the cheatsheet she made for them and she will then have a call with them to review it with them.

**Comment by sheridancbio** [comment]
@ritikakundra has reviewed this with the project managers
