### ISSUE TITLE
EKS Machine has Mail Server/Client for Notifications

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#574]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
We need a mail server/client setup on the EKS machine in order to send out import emails. 

## Technical Description (How are we going to achieve the above)
- Install same mail client as pipelines (w/ yum)
- Test messages (cbioportal-pipelines@cbio.mskcc.org)
- Maybe need a mail server (AVOID doing this ourselves!) 
- Come up with workflow for InfoSec
## Potential Issues
- Missing mail server
- Firewall Issues
### Technical Requirements
- Open SMTP Port on pipelines
### Outside People/Teams
Joanne (alter existing mail server)
DIGITS (new mail server)

**Comment by sheridancbio** [comment]
our current pipelines server (pipelines.cbioportal.mskcc.org) is using mailx for the command /bin/mail

The installed version is mailx 12.4 (gritter) 7/29/08

There is a yum package available on the eks pipelines node called mailx.x86_64 : Enhanced implementation of the mailx command

**Comment by sheridancbio** [comment]
test message has been sent, but not yet received:

[cbioportal_importer@ip-10-1-16-194 ~]$ mail cbioportal-pipelines@cbio.mskcc.org
Subject: Test Message from EKS node
This message was sent from the mail client on eks node 10.1.16.194 using only the mailx package (no sendmail MTA).

-- your friendly neighborhood importer
.
EOT

**Comment by sheridancbio** [comment]
I noticed that the node does have an MTA installed (from the start I guess) .. it is running postfix:
[root@ip-10-1-16-194 spool]# ps aux | grep postfix
root      2724  0.0  0.0  90288  4812 ?        Ss   May05   0:03 /usr/libexec/postfix/master -w
postfix   2726  0.0  0.0  90548  6764 ?        S    May05   0:00 qmgr -l -t unix -u
postfix   4087  0.0  0.0  90376  6628 ?        S    19:58   0:00 pickup -l -t unix -u

**Comment by sheridancbio** [comment]
I have confirmed that the postfix MTA is trying but is unable to connect to the cbio.mskcc.org server on port 25:

[root@ip-10-1-16-194 defer]# cat 7/78D3B808E3 

<cbioportal-pipelines@cbio.mskcc.org>: connect to cbio.mskcc.org[140.163.4.225]:25: Connection timed out
recipient=cbioportal-pipelines@cbio.mskcc.org
offset=243
status=4.4.1
action=delayed
reason=connect to cbio.mskcc.org[140.163.4.225]:25: Connection timed out

**Comment by sheridancbio** [comment]
We were informed that the firewall port was opened, but testing showed that port 25 is still not available for connections. This was reported back to infosec:
I did just test connection from the AWS dev account to the host cbio.mskcc.org and it seems to still be failing to open a TCP connection. Here is my test output:
[root@ip-10-1-16-194 7]# ncat -z -v cbio.mskcc.org 25
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connection timed out.
[root@ip-10-1-16-194 7]# echo $?
1
[root@ip-10-1-16-194 7]# host cbio.mskcc.org
cbio.mskcc.org has address 140.163.4.225
cbio.mskcc.org mail is handled by 10 cbio.mskcc.org.

I am not sure what that last line means "cbio.mskcc.org mail is handled by 10 cbio.mskcc.org", but I think it is the one and only mail server registered for handling mail to the domain (i.e. it handles its own mail services)

**Comment by sheridancbio** [comment]
Franklin reports that a request to Amazon to authorize outgoing port 25 SMTP traffic to be sent from our accounts has gone through. We should have valid mail sending now from our pipelines node.

In a follow up to this, Franklin requested that we dial down our firewall settings in the security groups for instances and databases. I have gone over all the dev account nodes. Two nodes were obsolete and were deleted. New security groups were created allowing access to particular service ports (ssh, http + https, mysql, mongo, redis) and assigned as appropriate. All nodes were added to the 'default' security group for the account which allows all ports to be open for intra-aws-instance connections.

Autoscalers use launch templates which reference security groups ... we don't have privileges to alter those or create new versions. Tomorrow we should try creating a new launch template with the right security group and switch the autoscaler over to use it.

I also plan to adjust the production account security groups tomorrow.
