### ISSUE TITLE
Dedicated Pipelines Node in EKS Production Environment

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#575]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
We need a pipelines mirror in production to import into production cluster. This machine will need to have all the necessary networking to connect to institutional systems and perform processes including imports, CVR, CRDB, Darwin, DDP, Redcap, OncoTree, CDD fetches. 

Accounts should be present for Rob, Avery, Manda, Angelica, Divya, Ben. 

## Technical Description (How are we going to achieve the above)
Ideally we could just use the service account to spin up a node (since it's not a cluster). However, it may be good to get a second opinion from DIGITS/InfoSec(?)

Once the node is up, run the scripts inside pipelines-configuration repo to do basic setup of directories and libraries. 
## Potential Issues
- Account restrictions that limit ec2 node creation
- Networking is not whitelisted by the needed groups
- CICD process enforced (unlikely)

**Comment by sheridancbio** [comment]
Node created using aws command line tool. First, a separate kubectl/aws context was created and used. Then a new ssh keypair was created, and then the instance for pipelines:

kubectl config set-context aws-eks-prod --user=service_account_user_name
kubectl config use-context aws-eks-prod

aws ec2 create-key-pair --key-name ProdPipelinesKey --query 'KeyMaterial' --output text > ProdPipelinesKey.pem

aws ec2 run-instances --image-id ami-0d5eff06f840b45e9 --count 1 --instance-type r5.xlarge --key-name ProdPipelinesKey --security-group-ids sg-048510ad90959f6ad --subnet-id subnet-0da1994f2fe4ef1a5 --tag-specifications 'ResourceType=instance,Tags=[{Key=msk:owner,Value=grossb1@mskcc.org},{Key=msk:cost-center,Value=#####},{Key=msk:resource-name,Value=cbioportal_cluster_infrastructure}]' 'ResourceType=volume,Tags=[{Key=msk:owner,Value=grossb1@mskcc.org},{Key=msk:cost-center,Value=#####},{Key=msk:resource-name,Value=cbioportal_cluster_infrastructure}]'

**Comment by sheridancbio** [comment]
unfortunately, the default security group prohibits incoming ssh connections. The next step will be to use the aws command line tool to create a security group and add inbound rules which allow ssh connections. Then the security group must be added to the instance network configuration.

**Comment by sheridancbio** [comment]
Instances can be named by creating a "Name" tag ... then the name shows up in the first column in the AWS console. It can be done like this:
aws ec2 create-tags --resources i-080eb785be280c97f --tags 'Key=Name,Value=pipelines'

**Comment by sheridancbio** [comment]
To create the security group we used:
aws ec2 create-security-group --cli-input-json '{"Description": "pipelines nightly import node", "GroupName": "ssh-access", "VpcId": "vpc-063daae43464a1615" }'

**Comment by sheridancbio** [comment]
To create the rule for the security group, we made a yaml skeleton file and applied it like this:
aws ec2 authorize-security-group-ingress --cli-input-yaml file://pipelines-create-security-group-rules.yaml

(file contents:)
GroupId: 'sg-018885054bcca8b4d' # The ID of the security group.
IpPermissions: # [REQUIRED] The IP permissions for the security group rule.
- FromPort: 0  # The start of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 type number.
  IpProtocol: 'tcp' # The IP protocol name (tcp, udp, icmp, icmpv6) or number (see Protocol Numbers).
  IpRanges: # The IPv4 ranges.
  - CidrIp: '0.0.0.0/0'  # The IPv4 CIDR range.
    Description: 'all sources IPv4' # A description for the security group rule that references this IPv4 address range.
  Ipv6Ranges: # [VPC only] The IPv6 ranges.
  - CidrIpv6: '::/0'  # The IPv6 CIDR range.
    Description: 'all sources IPv6' # A description for the security group rule that references this IPv6 address range.
  ToPort: 22 # The end of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 code.

**Comment by sheridancbio** [comment]
To link the security group to the instance we did this:
aws ec2 modify-instance-attribute --cli-input-yaml file://pipelines-set-security-groups.yaml

NOTE : this *replaces* all security groups with whatever is specified in the yaml file.

The yaml file we used is:
Groups: # [EC2-VPC] Changes the security groups of the instance.
- 'sg-048510ad90959f6ad'
- 'sg-018885054bcca8b4d'
InstanceId: 'i-080eb785be280c97f' # [REQUIRED] The ID of the instance.

**Comment by sheridancbio** [comment]
After doing the above, we were successful in logging in to the ec2 instance with:
ssh -i ProdPipelinesKey.pem ec2-user@10.1.21.42

and we have transferred a copy of ProdPipelinesKey.pem to our pipelines-credentials directory on pipelines.

**Comment by sheridancbio** [comment]
The running of create_user_accounts.sh and setup_system_dependencies.sh went fairly smoothly. We ran into problems getting the clone_repositories.sh script started.

First, we have not yet gotten the ssh keypair for accessing the public github.com for the cbioportalpipelines account. That was commented out, but then we discovered that the DNS resolution system was not configured properly for resolving names within the msk network (such as "data.cbioportal.mskcc.org"). It is not clear what is wrong - the name server routing table (possibly configured through a Transit Gateway record which cannot be examined in the production account) seems to not include resolution of names within the msk root domain.

For now, I have added all the IP addresses which we are using into /etc/hosts in order to get the cloning of data repositories going. We must ask for assistance configuring the Transit Gateway/nameserver appropriately.

**Comment by sheridancbio** [comment]
during cloning, I noticed that the production pipelines machine was created with too small of a disk volume (the default : 8gb was used). We did not have authorities to modify the disk volume with the aws command:
aws ec2 modify-volume --volume-type gp2 --iops 1000 --size 1024 --volume-id vol-0099ea6bf0493374a
An error occurred (UnauthorizedOperation) when calling the ModifyVolume operation: You are not authorized to perform this operation.
Without this authority we need to create a snapshot and relaunch an image from the snapshot.

**Comment by sheridancbio** [comment]
we are also not allowed to create snapshots:

aws ec2 create-snapshot  --description "resize-pipelines-volume" --volume-id "vol-0099ea6bf0493374a" --tag-specifications 'ResourceType=snapshot,Tags=[{Key=msk:owner,Value=grossb1@mskcc.org},{Key=msk:cost-center,Value=#####},{Key=msk:resource-name,Value=cbioportal_cluster_infrastructure}]'

An error occurred (UnauthorizedOperation) when calling the CreateSnapshot operation: You are not authorized to perform this operation.

**Comment by sheridancbio** [comment]
to get around this, I created a new volume and attached it:

aws ec2 create-volume --availability-zone us-east-1b --size 1196 --volume-type gp2 --tag-specifications 'ResourceType=volume,Tags=[{Key=msk:owner,Value=grossb1@mskcc.org},{Key=msk:cost-center,Value=#####},{Key=msk:resource-name,Value=cbioportal_cluster_infrastructure}]'

aws ec2 attach-volume --device /dev/xvdb --instance-id  i-080eb785be280c97f --volume-id vol-05a9bcb1361058fb8

[on node]
fdisk /dev/xvdb
n p 1 [default - allocate all disk] w

mkfs -t ext2  /dev/xvdb1

vim /etc/fstab
add:
UUID=8e626103-3e22-469f-96c3-1549011cd3a2     /data       ext2   defaults          1   2

mkdir /data
mount -a

**Comment by sheridancbio** [comment]
pipelines node in production cluster was deleted and recreated with:
aws ec2 run-instances --image-id ami-0d5eff06f840b45e9 --count 1 --instance-type r5.xlarge --key-name ProdPipelinesKey --security-group-ids sg-048510ad90959f6ad sg-018885054bcca8b4d --subnet-id subnet-0da1994f2fe4ef1a5 --tag-specifications 'ResourceType=instance,Tags=[{Key=msk:owner,Value=grossb1@mskcc.org},{Key=msk:cost-center,Value=#####},{Key=msk:resource-name,Value=cbioportal_cluster_infrastructure},{Key=Name,Value=pipelines}]' 'ResourceType=volume,Tags=[{Key=msk:owner,Value=grossb1@mskcc.org},{Key=msk:cost-center,Value=#####},{Key=msk:resource-name,Value=cbioportal_cluster_infrastructure},{Key=Name,Value=pipelines}]' --placement 'AvailabilityZone=us-east-1b' --instance-initiated-shutdown-behavior stop --private-ip-address 10.1.21.43 --block-device-mappings 'DeviceName=/dev/xvda,Ebs={DeleteOnTermination=true,VolumeSize=1196,VolumeType=gp2}'

This allows the node to have a single shared root volume large enough to hold all data.

After creation, the scripts create_user_accounts.sh was copied to the machine and run by root like this:
./create_user_accounts.sh 'wanga5,,ir,Avery.Wang' 'sheridan,,ir,Robert.Sheridan' 'wilson,,ir,Manda.Wilson' 'grossb,,ir,Benjamin.Gross'

Then the script setup_system_dependencies.sh was copied and run by root as well.

Entries were added to /etc/hosts to temporarily work around our dns resolution problems like this:
127.0.0.1       localhost localhost.localdomain localhost4 localhost4.localdomain4
::1             localhost6 localhost6.localdomain6
140.163.153.185 pipelines.cbioportal.mskcc.org data.cbioportal.mskcc.org
140.163.135.60  ddp.mskcc.org
140.163.4.228   ramen.cbio.mskcc.org
140.163.153.65  dashi.cbio.mskcc.org
140.163.153.183 dashi2.cbio.mskcc.org
172.22.242.239  lynx.mskcc.org
172.22.242.234  draco.mskcc.org
10.254.102.203  plcrdbd2.mskcc.org
140.163.170.51  pidvudb1.mskcc.org
172.23.235.224  github.mskc.org
140.163.4.225   cbio.mskcc.org

The partial success repo clones were unpacked from a tarball and then on top of those the clone_repositories.sh script was run as user cbioportal_importer:
./clone_repositories.sh

**Comment by sheridancbio** [comment]
We have decided to manually clone the github.com repositories using username/pw authentication while we wait to hear back from digits about ssh protocal to github.com.

We are going to hold off on updating the create_repositories script until we hear back.

For Manda: The last remaining cloning repository step needed is to clone datahub repo from github.com into /data/portal-cron/cbio-portal-data ... the command to do that looks like this:

git clone https://cbioportalpipelines:PASSWORD@github.com/cBioPortal/datahub.git
Remember to encode any non-alphanumeric characters using URL encoding.

**Comment by sheridancbio** [comment]
During the cloning of the data repositories, we ran into a limit on LFS transfer while cloning datahub.

We were seeing odd behavior with the LFS pointer files not automatically being converted to the object data during pull operations.

These settings were added to ~/.gitconfig:
[filter "lfs"]
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge -- %f
        process = git-lfs filter-process
        required = true
[credential]
        helper = cache

Also, the repository "dmp-2021" (which was cloned) disappeared. We are attempting to reclone it using the new lfs config settings.

**Comment by sheridancbio** [comment]
After receiving errors in the cbioportal_importer account trying to do "git lfs pull" with the genie repo, I removed those lines from ~/.gitconfig and was able to successfully do a git clone <reference> ; git lfs pull in each repo.

The Importer fetch operation for datahub repos is implemented in DatahubServiceImpl.java [in Pipeines repo]. It is implemented like this:
executeCommand(repository, "git-lfs pull origin " + gitBranchName);

executeCommand is implemented as runtime.getRuntime().exec(command ...)

I am testing proper function of this by adding a commit to an LFS enable repo and seeing if "git-lfs pull" functions correctly ... i.e. gets the full data and not just the link file.

**Comment by sheridancbio** [comment]
Ok, after additional testing, I think the fetchers in the importer code base are succeeding because of the call prior to get-lfs pull origin.

The function pullUpdate() first calls "prepareRepository(repo)" which executes these three commands:
git checkout .
git clean . -fd
git reset --hard origin/branchname

The ```reset``` command above causes a full download of any needed LFS objects and a filtering / smudge operation on all of them. After doing that, the ```git-lfs pull origin master``` actually doesn't matter anyway because you have already set the local clone to exactly match the remote branch.

So this is how the importer keep the repos up to date.

**Comment by mandawilson** [comment]
`git-lfs pull` seems to not successfully pull down changes to lsf files even though `git lfs pull` does.  Our import scripts use `git-lfs pull` which works on pipelines -- is it not working on pipelines?  Can we test it?  Use `pipelines-testing` to test on pipelines.  Make sure it is done in a data_mutations_extended file (a file controlled by lsf).

Also:

Build an importer binary on production node.  See if it fails to fetch.

When `.gitconfig` is there a git clone only gets linked files, doesn't convert them into the real data.  If that file is not there, it works fine.  Confirm this?  Make sure we don't have that file.  How did it get there?

**Comment by mandawilson** [comment]
@sheridancbio the importer code on pipelines does work because before it calls `git-lfs pull origin master` it calls `git pull origin master`:

```
prepareRepository(repository);
String gitUpToDate = getValue(executeCommand(repository, "git pull origin " + gitBranchName), gitUpToDatePattern);
// always run git-lfs pull origin <branch> to ensure git-lfs managed file
// contents show actual data, not pointer file reference info
executeCommand(repository, "git-lfs pull origin " + gitBranchName);
```

I tested the full set of steps on branch `test-git-lfs-pull` in `datahub` (I don't have write access to `pipelines-testing`) and it works:

```
git checkout .
git clean . -fd
git reset --hard origin/test-git-lfs-pull
git pull origin test-git-lfs-pull
git-lfs pull origin test-git-lfs-pull
```

The `git pull origin master` pulls the changes, `git-lfs pull origin master` makes sure the files are not pointers (seems like anyway).
