### ISSUE TITLE
Production Keycloak Available (2)

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#577]
- #5## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
We need Keycloak available in production for authentication.

Keycloak server up for use in the production cluster -- should either be backed by MySQL or have a very detailed identifiable contained card for migrating when possible.

## Technical Description (How are we going to achieve the above)
- [x] Setup RDS Node for Keycloak
- [x] Use Helm to init Keycloak (ideally from the prod EC2 Pipelines Mirror)
- [x] Create Triage Realm/IDP
- [x] Create MSK Realm/IDP
- [x] Create Private Realm/IDP (sclc)
- [x] move DB off of RDS node into EC2 instance

## Potential Issues
- SSL Issue, can't get a valid certificate due to being behind firewall/private IP, maybe fixed in prod
### Technical Requirements
- Valid certificate on the keycloak server/db?
### Outside People/Teams
Neeraj
### Issues
- #573 (Working Prod EKS Cluster)
- #575 (Working Prod EKS Node Pipelines Mirror)
- # 579 (SSL Cert Working)

**Comment by sheridancbio** [comment]
As part of deploying keycloak, a new rds database must be made available.

**Comment by mandawilson** [comment]
```
aws ec2 create-security-group --group-name "mysql-access" --description "access mysql port from aws prod account, pipelines.cbioportal.mskcc.org, dashi-dev.cbio.mskcc.org" --vpc-id "vpc-063daae43464a1615"
```

**Comment by mandawilson** [comment]
```
aws rds create-db-subnet-group --db-subnet-group-name "all-subnets" --db-subnet-group-description "all subnets" --subnet-ids '["subnet-0a374339b483afb2a", "subnet-0f99821552c289edb", "subnet-0da1994f2fe4ef1a5"]'
```

**Comment by mandawilson** [comment]
```
aws rds create-db-instance --cli-input-yaml file://keycloak-rds-create-db-instance.yaml 
```

**Comment by sheridancbio** [comment]
when we made the security group rules [above] we added the three subnets but not pipelines or dashi-dev. I added rules for them now and checked the changes in to the repo.

**Comment by averyniceday** [comment]
we've upgraded keycloak to the newest release (06/30) - does not have the restart problem mentioned earlier.

Added `use-forwarded-headers` to Ingress setup.

**Comment by averyniceday** [comment]
all the setup minus the IDP is done, I've messaged Nishant about getting PingID up and running. Waiting on a response.

**Comment by averyniceday** [comment]
(3)
