### ISSUE TITLE
Fix GitHub Actions on Datahub for Gzipping

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#590]
## Client (Who is making the request)
Curation Team
## Issue/Deliverable
Update AccessKeys on AWS

**Comment by mandawilson** [comment]
Avery found the fix here: https://github.com/actions/runner/issues/503

Our datahub repo is currently over the bandwidth limit so The GitHub action is still failing and will for the rest of today.

Once the bandwidth limit is reset (hopefully tomorrow) we need to confirm that this works.  Then this card will be done.

A new card should be made to either re-zip all studies (maybe create a new github action for that) or only re-zip the ones that are out of date in S3.
