### ISSUE TITLE
Update All Zipped Datahub Studies in S3

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#591]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
All studies repushed into S3

**Comment by mandawilson** [comment]
Manually trigger a zip and copy of all studies to S3 by going to the datahub `Actions` tab, clicking on the `Select Workflow` button, select `Manually zip all studies on the master branch`, and then click on the `Run workflow` button.  This will only checkout the `master` branch studies even if you are running the workflow from another branch.
