### ISSUE TITLE
fix failing jenkins tests

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#593]
PRs were merged this sprint by overriding required jenkins integration tests.

We should make sure all of these recently failing tests run on the master branch of the relevant repositories:
--------------------------------------------------------------------------
fetcher-redcap-schema-integration-test (1789)
http://dashi-dev.cbio.mskcc.org:8090/job/fetcher-redcap-schema-integration-test/1789/

3:06:26 GIT_BRANCH is 'origin/pull/850/head'
13:06:26 getting tags for pull-request 850
13:06:27 ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
13:06:27 java.lang.reflect.InvocationTargetException
13:06:27 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13:06:27 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13:06:27 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13:06:27 	at java.lang.reflect.Method.invoke(Method.java:498)
13:06:27 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
13:06:27 	at java.lang.Thread.run(Thread.java:745)
13:06:27 Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/spi/Terminable
13:06:27 	at java.lang.ClassLoader.defineClass1(Native Method)

NOTE : this may be because of recent dependabot updates to libraries .. perhpas https://github.com/knowledgesystems/cmo-pipelines/pull/827

--------------------------------------------------------------------------
cdd-integration-test
577
http://dashi-dev.cbio.mskcc.org:8090/job/cdd-integration-test/577/

--------------------------------------------------------------------------
genome-nexus-annotation-pipeline 789
http://dashi-dev.cbio.mskcc.org:8090/job/genome-nexus-annotation-pipeline/789/
16:30:23 Checking if 'as1000' is a member of team 'developers', members are: jjgao, inodb, dionnezaal, mandawilson, pieterlukasse, onursumer, zhx828, sheridancbio, ao508, leexgh, averyniceday, cbioportalpipelines, divyamadala30
16:30:23 User 'as1000' on PR '173' is NOT a member of team 'developers' for repository 'genome-nexus/genome-nexus-annotation-pipeline'
16:30:23 User is NOT a trusted user

NOTE .. it seems like this final case is not a failure but is proper behavior to refuse to run code from an untrusted developer.

**Comment by mandawilson** [comment]
A bump in the version number of log4j-core in com-pipelines caused the CDD integration tests to fail: https://github.com/knowledgesystems/cmo-pipelines/commit/bd953c3792c689791a66e6a8bc51e6ff889042c0

**Comment by mandawilson** [comment]
All tests besides genome-nexus-annotation-pipeline are now working.  We are waiting for Ino to approve `as1000` as a trusted developer.
