### ISSUE TITLE
Build Separate Importer for Trying File Renaming

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#603]
## Client (Who is making the request)
Curation Team

## Issue/Deliverable
Build an importer that points to different db (hgnc on dashidev) and spreadsheet for testing file renaming. Issues that come up will be a separate card.

**Comment by sheridancbio** [comment]
This has been done. One hiccup was needing to update both importer.properties and also applicationContext.xml. The copy of the spreadsheet which has the new datatype records can be seen/edited here: https://docs.google.com/spreadsheets/d/155FmKK7SmTFPFtlRfaj7t6SA1nPZz19pfNzoFxyME6M

Our build-importer-jars test study was imported to the hgnc database on dashi-dev ... and then deleted with the new spreadsheet. It seems to work smoothly and Ramya reports that a real import also worked.
