### ISSUE TITLE
Fix Broken Importer

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#619]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Importer code (pipelines) is broken after a fix deployed in February. New builds will compile successfully but suddenly exit during import. 

Done condition is that the codebase is back in working state (new builds on the head of master will successfully run)

Cap effort to 1.5 days, otherwise see if the change was necessary and if it can be rolled back (with Ino).

## Technical Description (How are we going to achieve the above)
Unsure -- this fix was created/merged by Ino and Angelica - we can check what/why the fix was needed and go from there. 
## Potential Issues
Not sure how many commits have occurred since the original fix in Febraury
### Outside People/Teams
Ino
Angelica

**Comment by mandawilson** [comment]
Please review: https://github.com/knowledgesystems/pipelines/pull/416
