### ISSUE TITLE
Get SCLC and Private on EKS

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#621]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Have the deployment files (k8s yamls, k8s config maps, keycloak volumes setup)
Does not necessarily have to be running, but should be able to be dpeloyed using a kubectl apply -f blah

**Comment by averyniceday** [comment]
SCLC is up now with Google as its IDP (connected through keycloak) - have not formally requested for it to be publicly routable yet

**Comment by sheridancbio** [comment]
to look at:
- deployment yaml
- cgds_gdac database is already present as static snapshot
- keycloak private realm needs to be populated using a dump from the other keycloak (aws account)
- ingress traffic need to be routed [not yet involve Franklin yet] - private.cbioportal.aws.mskcc.org
- aws route 53 entry needed for private.cbio...
- properties map [ config_map] for private needs to be loaded into kubernetes (has authentication xml link)
- redis configuration - needs to be established for private, including     - -Dredis.database=3 ??
