### ISSUE TITLE
Add Keycloak Admin for SCLC realm

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#631]
We need to setup Kelly Clarke as an admin to the SCLC portal so she can add users and assign roles as needed.

clarkek@mskcc.org

**Comment by averyniceday** [comment]
Make sure curation and user have training session

**Comment by mandawilson** [comment]
I added clarkek@mskcc.org to both keycloaks and granted her permission to add users and assign roles.  Note she also has a gmail account in both keycloaks kellyaclarke87@gmail.com which does not have the add users and assign roles permission.

https://keycloak.cbioportal.mskcc.org/auth/admin/external/console/#
https://keycloak.cbioportal.org/auth/admin/external/console/#

If you don't add the # at the end of the above URLs you get a forbidden error.
