### ISSUE TITLE
Triage Portal login page adjustments

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#642]
The login page of the triage portal links to the SCLC google registration form.  I actually don't think we need the "if you are a new user heading...".  Lets discuss.

![image.png](https://images.zenhubusercontent.com/570fd610bf93871ccd99739b/c731c198-ce32-48a0-bb5e-253aa4c7f454)

**Comment by averyniceday** [comment]
Done Condition:
SCLC: Google Login + Spreadsheet Login
Triage: PingId + Ritika email
