### ISSUE TITLE
Fix 413 Error

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#650]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Aaron noticed 413 error being thrown by https://triage.cbioportal.mskcc.org/study/summary?id=msk_met_2021

This should not throw 413s

**Comment by mandawilson** [comment]
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size
Custom max body size ¶

For NGINX, an 413 error will be returned to the client when the size in a request exceeds the maximum allowed size of the client request body. This size can be configured by the parameter client_max_body_size.

To configure this setting globally for all Ingress rules, the proxy-body-size value may be set in the NGINX ConfigMap. To use custom values in an Ingress rule define these annotation:


nginx.ingress.kubernetes.io/proxy-body-size: 8m

**Comment by mandawilson** [comment]
In the triage portal 413 error I see "Content-Length: 1288808" which is over 1mb, the default maximum:

https://docs.giantswarm.io/advanced/ingress/configuration/
A 413 error will be returned to the client when the size in a request exceeds the maximum allowed size of the client request body. This size can be configured by the parameter client_max_body_size and is set to 1m (1 Megabyte) by default.

To configure this setting globally for all Ingress rules, the proxy-body-size value may be set in the NGINX ConfigMap.
