### ISSUE TITLE
Deploy MSK Portal to EKS

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#652]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Same steps as all other portals (redis enabled)

## Technical Description (How are we going to achieve the above)
Configmaps, deployment yamls, etc.
## Potential Issues
Make sure that we have a clearly outlined fallback plan before switching over public URL

**Comment by averyniceday** [comment]
- [x] msk prod
- [x] msk beta
- [x] acc
- [x] glioma
- [x] immunotherapy
- [x] kras
- [x] pdx
- [x] poetic
- [x] prostate
- [x] su2c
- [x] sclc
- [x] target

**Comment by averyniceday** [comment]
- [x] deploy session redis
- [x]  make the configmap (cbio-portal-data/k8s-config-vars)
- [x]  create the client inside keycloak (keycloak.cbioportal.mskcc.org) MEW: done all clients but did not do saml keys stuff
- [x]  make the keycloak configmap (git-repos/portal-configuration/properties)
- [x]  make deployment (k8s-knowledge-systems) NOTE: make sure you update all properties e.g. -Dpriority_studies for each study
- [x]  update ingress (w/ AWS internal url) + Route 53
- [x]  deploy deplyoment
- [x]  fix anything comes that comes up

**Comment by averyniceday** [comment]
(5)

**Comment by mandawilson** [comment]
- [ ] prostate client still needs mpcproject_van_allen_2021 role added to assigned roles (it isn't in realm roles)

**Comment by mandawilson** [comment]
- [x] caching is turned off -- shouldn't it be on?
- [x] data access token for msk portals

**Comment by mandawilson** [comment]
- [x] increase max_allowed_packet

Viewing MSK impact fails:

```
Cause: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (4725002 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
; Packet for query is too large (4725002 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.; nested exception is com.mysql.jdbc.PacketTooBigException: Packet for query is too large (4725002 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.] with root cause
com.mysql.jdbc.PacketTooBigException: Packet for query is too large (4725002 > 4194304). You can change this value on the server by setting the max_allowed_packet' variable.
```
