### ISSUE TITLE
Debug / workaround failure to restart persistence redis services

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#658]
The restart script uses commands of this kind to restart the persistence redis services:

kubectl set env statefulset $cache_service --env="LAST_RESTART=$(date)"

For triage, both the master and replicas services are attempted to be restarted, but restarts frequently fail.

The more frequent error leaves the master redis pod with a status such as:
Warning FailedAttachVolume 3m5s attachdetach-controller Multi-Attach error for volume "pvc-b77ac439-12f3-4fac-9015-d3cf895aff5d" Volume is already exclusively attached to one node and can't be attached to another

Other observed failure status was:
MountVolume.WaitForAttach failed for volume "pvc-b77ac439-12f3-4fac-9015-d3cf895aff5d" : volume attachment is being deleted

After a great number of attempted "kubectl delete pod" commands delete all (and various subsets) of the persistence redis pods, the service finally became available and ready again. But it was observed to sit in a non-functional state for several hours between attempts to re-establish normal function.

For now the triage restart has been adjusted to only attempt restart of the master service --- but this may fail again tomorrow.

**Comment by averyniceday** [comment]
- [x] Update Redis Persistence Deployment
- [x] Check in Redis Yaml File
- [x] PR to Revert cmo-pipeline changes
- [x] Deploy new cmo-pipeline script
- [x] Confirm working

**Comment by sheridancbio** [comment]
work complete - scripts tested in production for triage import pipeline (pods for backend and for redis persistence services were all restarted smoothly)

Other uncommitted script changes in the deployment directory included in PR.
https://github.com/knowledgesystems/cmo-pipelines/pull/888
