### ISSUE TITLE
resolve : eks database connection overload

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#660]
I am seeing failures for some of the pods running in the eks portal. All deployments have the same username/password settings in the deployment settings so I am guessing the issue here is that every pod is opening up a separate pool of connections to the database, and there are currently 16 pods running (which will probably be increased when we add replicas for msk portal and maybe internal portal). Each pod is opening up a connection pool of perhaps 20? ready connections? That would be something like 320 connections, which may be above the configuration limit. The shared tomcat resource allowed all of the schultz tomcats to share a common pool, but that is no longer the case.

We probably need to figure out a way to increase the total number of connections allowed to the mysql server running on the pipelines pod, or we need to scale down the size of the pools of open connections in each pod. (or some combination)

We might also spawn off a cloned cgds_gdac database in a separate mysql server (or rds node) which would be static and would only back the static portals from the schultz-tomcat group.

**Comment by sheridancbio** [comment]
HTTP Status 500 – Internal Server Error
Type Exception Report

Message Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException:

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'cbio_user'@'ip-10-1-20-174.ec2.internal' (using password: YES)
### The error may exist in URL [jar:file:/target/tomcat.8888/webapps/expanded/WEB-INF/lib/persistence-mybatis-0-unknown-version-SNAPSHOT.jar!/org/cbioportal/persistence/mybatis/StudyMapper.xml]
### The error may involve org.cbioportal.persistence.mybatis.StudyMapper.getStudies
### The error occurred while executing a query
### Cause: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: Access denied for user 'cbio_user'@'ip-10-1-20-174.ec2.internal' (using password: YES)

**Comment by mandawilson** [comment]
```
mysql> SHOW VARIABLES LIKE "max_connections";
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 4190  |
+-----------------+-------+
1 row in set (0.00 sec)
```
