### ISSUE TITLE
Convert Oncotree into a Docker Image 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#668]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Can run oncotree out of a docker image (needed for eventual move to k8s)

## Potential Issues
Firewall will need to be adjusted - need open ports to topbraid server
Redirecting oncotree.info
* For another card: migrate to prod topbraid server

**Comment by mandawilson** [comment]
TODO:
- [ ] https://github.com/cBioPortal/oncotree/pull/250
- [x] confirm our code changes did not break jenkins
- [x] update application.properties to only have ehcache mvn filtering props
- [x] checkin oncotree service yaml, oncotree configmap
- [x] checkin code changes (which is only dockerfile introduction)
- [ ] update buildscript to build (same as before) but add a docker built and push
