### ISSUE TITLE
Investigate CVR Fetch Failure

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#670]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Find out way CVR fetch is broken

**Comment by sheridancbio** [comment]
This was determined (by @ao508) to be a failure inside the CVR system. The 500 status response comes down with a stack trace which reports a non-decodable unicode character 0xA0 encountered during the CVR system processing of the request for the mskimpact somatic (non-germline) samples. It was reported to Aijaz in the cvr slack channel.
