### ISSUE TITLE
Make HGNC dashi-dev test db work

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#681]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Can import into HGNC database (limited to a database migration and importer rebuild, deploy a WAR but don't debug if it's not related - replan if scope changes)

**Comment by mandawilson** [comment]
We have updated the HGNC importer on dashi-dev.  You can run it by going to /data/portal-cron/scripts and running ./request-hgnc-import.  You can watch the log file with tail -f /data/portal-cron/logs/hgnc-importer.log.  It imports into the dashi-dev cgds_hgnc database.  The website that points to that database is now found here: http://dashi-dev.cbio.mskcc.org:8080/hgnc/.
