### ISSUE TITLE
Prepare Presentation for EKS

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#684]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Divvy up slides - who's saying what.

**Comment by sheridancbio** [comment]
Topics for EKS talk:
Avery : why we are doing it
Avery : Azure devops to create cluster
Rob : Keycloak authentication
Avery : Loadbalancers and Ingress
Avery : SSL traffic / AWS certificates
Rob : IP Address exhaustion issue
Rob : future improvements
