### ISSUE TITLE
get cdd/oncotree off of dashi/dashi2 (Franklin)

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#701]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
cdd/oncotree are running in the digits eks cluster account and the dashi/dashi2 oncotree-tomcat installs are shut down.

I've talked to Franklin about this and told him we'll be addressing this in the next few weeks (12/1-12/15?)
CDD and Oncotree docker repos have been created with images pushed 

## Technical Description (How are we going to achieve the above)
Per Franklin:
- [ ] CNAME record to public ALB inside google domains
- [ ] get a cert and validate both on Franklin's end and in Google domains (for oncotree)

## Potential Issues
- Franklin has a case where another user was managing names on godaddy and was unable to create a CNAME record pointed to ALB (and had to use domain forwarding which we don't want for oncotree)

- not sure how to get the cert/attach the cert -- think can only attach one cert per listener so might have issues if we cannot get oncotree.info under the same cert that we currently use

**Comment by mandawilson** [comment]
- [x] CDD and Onctree deployments should be switched to main docker repo - not Manda's or Avery's docker repo
- [ ] Set up test.oncotree.info - MSKCC knowledge system's email?
- [ ] Point to Franklin's public load balancer
- [x] Put test.oncotree.info into our ingress
- [ ] Certificate should work for *cbioportal.mskcc.org and *oncotree.info (maybe lets encrypt)
