### ISSUE TITLE
Fix CVR Fetch

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#727]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
CVR operations can run at specified times that we have explicitly defined and not fail 
## Technical Description (How are we going to achieve the above)
Capture response for failed or stalled fetch. Use that to communicate with CVR team to identify the problem. 

At the very least, add a timeout so a stall does not prevent rest of overnight processes from running.

Background Info:
We have had issues consuming samples around 2am. We have temporarily introduced a stopgap to stop cvr operations in that window -- but this is not a permanent fix and we have not had explicit confirmation that a server restart is the cause of the issue. 

We need to work more closely with CVR to determine **exactly** (reliably reproducible) why are cvr operations have been failing. If it is a timing issue we set explicit time windows -- or if it's a date issue we should log and create a workflow with CVR to better prevent it.

**Comment by mandawilson** [comment]
https://github.com/knowledgesystems/cmo-pipelines/pull/907/files
