### ISSUE TITLE
Handle HTML errors in all RestTemple requests in CVR (easy win)

### ISSUE THREAD

**Issue by mandawilson** [knowledgesystems/pipelines-scrum#743]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
In all RestTemplate requests we should handle getting an exception that includes an HTML response, e.g. https://github.com/knowledgesystems/cmo-pipelines/pull/907/files.  We might also want to output the status code.

Note (from: https://github.com/spring-projects/spring-framework/issues/24964): 
```
IOException or HttpMessageNotReadableException are problems while reading the response body which can only be read once. This is why the code here raises a plain RestClientException. By contrast for 4xx and 5xx we raise RestClientResponseException (or one of its sub-classes) with the body.
```

**Comment by sheridancbio** [comment]
@averyniceday I have approved the PR .. feel free to merge and deploy (or I can do it if you prefer)
