### ISSUE TITLE
Explore Migration to production TopBraid 

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#757]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
TopBraid concepts for supporting Oncotree & CDD web services are running on production TopBraid server.
Find out barriers that may come up when migrating to TopBraid - version, permissions, etc. 
### Outside People/Teams
Per Molly Maloy, reach out to Tom Kim and Javier Villarreal on the TopBraid team for any assistance.

**Comment by sheridancbio** [comment]
We have access to the production server and it is running the same exact version of topbraid as the test server.

I was able to create Ontologies and Topologies and loaded in the Ontology definitions and Topology data for a version of Oncotree. I issued the relevant SPARQL query from our oncotree codebase into the SPARQL query webpage and go the expected results. I don't see any difficulties transitioning to the production TopBraid server.

The service account we use also is set up on the production server and I was able to login and view using it.
