### ISSUE TITLE
Fix OncoKB Annotation in Prod 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#763]

**Comment by averyniceday** [comment]
hypothetically because running from pipelines and dmp improter is no longer present to pull the repo

**Comment by sheridancbio** [comment]
mskimpact MAF had >500000 variants. Processing was failing with broken connections:
  File "/data/portal-cron/git-repos/oncokb-annotator/AnnotatorCore.py", line 208, in makeoncokbpostrequest
    timeout=REQUEST_TIMEOUT)requests.exceptions.ConnectionError: ('Connection aborted.',
...
RemoteDisconnected('Remote end closed connection without response'))

This PR eases the load by reducing batch size and increasing timeouts:
https://github.com/oncokb/oncokb-annotator/pull/145

The full Onckb annotation on the mskimpact study completed smoothly with these changes.
