### ISSUE TITLE
Moving Files Off Ramen and onto a Protected S3 (Immediate)

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#764]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
No dependency on ramen for downloadable files
- [x] inventory on what's on Ramen
- [x] oncokb annotated files
- [x] update link on datahub
## Technical Description (How are we going to achieve the above)
Make a decision and move things into S3 -- alert and hold ramen as a backup for X time

**Comment by averyniceday** [comment]
Rotate passwords on monthly basis

**Comment by sheridancbio** [comment]
There is a new repository called okcokb-annotated-msk-impact in the msk enterprise github with the files which used to be distributed off of download.cbioportal.org (ramen). We went through all the other files and reminded the owners that they had files there ... any cleanup of those (if needed) could be a separate card. We did not hear back from Joanne about the configuration of the apache web server so we are not sure what other ramen dependencies we have, but the two that we know of and are in the process of switching to the digits eks account are:
- oncotree
- cdd

A new team was created for users who need access to dmp-2022 ... and the team was given access to the new repository oncokb-annotated-msk-impact
