### ISSUE TITLE
Moving Redcap into EKS Environment

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#765]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Redcap is hosted and running inside EKS Environment - this can either be as apache/php config or k8s/cloudformation stack - should at least attempt installing newest version if possible 
## Potential Issues
Networking (?)

**Comment by mandawilson** [comment]
- [x] Add install apache to pipelines setup script
- [x] Add install PHP to pipelines setup script
- [x] Add redcap database to database backup script

**Comment by mandawilson** [comment]
- [x] Approve, merge, and deploy: https://github.com/knowledgesystems/cmo-pipelines/pull/918
- [x] Approve and merge: https://github.mskcc.org/knowledgesystems/portal-configuration/pull/5
