### ISSUE TITLE
Migrating to Production TopBraid 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#773]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Data sits inside production topbraid and prod applications (on dashi and dashi2) and test applications are running off the new server (properties checked in) 

update both properties files (tomcat war) and config maps (eks deployment)

**Comment by sheridancbio** [comment]
since cdd and oncotree were adjusted to run dockerized and properties were removed from portal.properties, in order to build the warfiles for dashi/dashi2 it was necessary to revert pipelines-configuration repo to commit 9185c73a1f7a3da80fc9b185f0c45665bdcf2868 temporarily.

**Comment by sheridancbio** [comment]
The ehcache contents from before for the unit tests were apparently corrupted. I had to provide a fresh directory for cdd ehcache persistence. (/data/ehcache/cdd_test)

**Comment by sheridancbio** [comment]
New taxonomies and ontologies are available on the production topbraid server (http://evn.mskcc.org) ... one change needed was to adjust the graph id for oncotree_current ... the new taxonomy URI went in as "oncotree_development" on creation, so the new graph id was adjusted in Oncotree-Versions to match.

Deployments were made to dashi/dashi2 tomcat (backing up the previous version)

**Comment by sheridancbio** [comment]
There is no natural place for these changes anymore in the pipelines-configuration repo. If this needs to be done again, checkout the changeset reference above and apply these changes:
--- a/properties/clinical-data-dictionary/application.properties
@@ -1,6 +1,6 @@
-# the knowledge systems topbraid server sparql endpoint (e.g. http://test.evn.mskcc.org/edg/tbl/sparql)
-topbraid.knowledgeSystems.serviceUrl=http://test.evn.mskcc.org/edg/tbl/sparql
-topbraid.knowledgeSystems.loginUrl=http://test.evn.mskcc.org/edg/tbl/sparql
+# the knowledge systems topbraid server sparql endpoint (e.g. http://evn.mskcc.org/edg/tbl/sparql)
+topbraid.knowledgeSystems.serviceUrl=http://evn.mskcc.org/edg/tbl/sparql
+topbraid.knowledgeSystems.loginUrl=http://evn.mskcc.org/edg/tbl/sparql

--- a/properties/oncotree/application.properties
@@ -3,7 +3,7 @@ springfox.documentation.swagger.v2.path=/api-docs
 # for topbraid e.g. https://evn.mskcc.org/evn/tbl/sparql
-topbraid.url=http://test.evn.mskcc.org/edg/tbl/sparql
+topbraid.url=http://evn.mskcc.org/edg/tbl/sparql
