### ISSUE TITLE
CVR ARCHER SV updates

### ISSUE THREAD

**Issue by ao508** [knowledgesystems/pipelines-scrum#784]
Requirements:
- Must still support the old SV schema because any old ARCHER samples that are requeued will still have SV data in the old schema
- Fix mapping of JSON attributes that mean the same thing to their corresponding staging file column header (i.e., `site1_gene` and `gene1` mean the same thing and should both be considered when populating the value written to the staging file) 
- Update staging file column headers to match the expected column headers in the cbioportal [SV data importer](https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportStructuralVariantData.java)
  - As part of this we must also update the column headers of the staging files checked into the dmp 2021 data (git) repo

**Comment by mandawilson** [comment]
https://github.com/knowledgesystems/cmo-pipelines/pull/930
