### ISSUE TITLE
Remove cvr json files from DMP-2022 repos

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#797]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Move cvr json files (including germline) from the primary DMP-2022 and relocate to a more restricted repos.

**Comment by averyniceday** [comment]
https://github.mskcc.org/knowledgesystems/dmp-2022

**Comment by mandawilson** [comment]
https://github.com/knowledgesystems/cmo-pipelines/pull/954
