### ISSUE TITLE
Brainstorm DB Migration Script

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#817]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Migration script for migrating fusions profile to sv
Determine what patterns/names are used internally and how we can migrate them
How easily are mutation records converted to SV records (what data will be dropped or unavailable)

**Comment by averyniceday** [comment]
from 10.1.141.114:  `mysql -u cgds_admin -p` using `cgds_gdac`
```
select count(*) from mutation_event where mutation_type="Fusion";
select * from genetic_profile where genetic_alteration_type="FUSION";
select * from genetic_profile where genetic_alteration_type="STRUCTURAL_VARIANT";
```
We see alot of structural_variant genetic profiles and ~6 fusion fusion genetic_profiles

**Comment by mandawilson** [comment]
It looks like there are fusion datatypes for MUTATION_EXTENDED, FUSION, and STRUCTURAL_VARIANT genetic alteration type.

1) How many of each?
2) Are the actual mutation records the same structure in all of them?

**Comment by mandawilson** [comment]
Where are `mutation_event.MUTATION_TYPE="Fusion"` records coming from?

`select 
    genetic_profile.GENETIC_ALTERATION_TYPE, 
    genetic_profile.DATATYPE,
    mutation_event.MUTATION_TYPE,
    count(mutation_event.MUTATION_EVENT_ID)
    from mutation_event, mutation, genetic_profile
    where
        genetic_profile.GENETIC_PROFILE_ID=mutation.GENETIC_PROFILE_ID and
        mutation.MUTATION_EVENT_ID=mutation_event.MUTATION_EVENT_ID and
        mutation_event.MUTATION_TYPE="Fusion" 
    group by
    genetic_profile.GENETIC_ALTERATION_TYPE,
    genetic_profile.DATATYPE,
    mutation_event.MUTATION_TYPE;`

10.1.141.114 cgds_gdac:
`
mysql> select genetic_profile.GENETIC_ALTERATION_TYPE, genetic_profile.DATATYPE, mutation_event.MUTATION_TYPE, count(mutation_event.MUTATION_EVENT_ID) from mutation_event, mutation, genetic_profile where genetic_profile.GENETIC_PROFILE_ID=mutation.GENETIC_PROFILE_ID and mutation.MUTATION_EVENT_ID=mutation_event.MUTATION_EVENT_ID and mutation_event.MUTATION_TYPE="Fusion" group by genetic_profile.GENETIC_ALTERATION_TYPE, genetic_profile.DATATYPE, mutation_event.MUTATION_TYPE;

+-------------------------+----------+---------------+-----------------------------------------+
| GENETIC_ALTERATION_TYPE | DATATYPE | MUTATION_TYPE | count(mutation_event.MUTATION_EVENT_ID) |
+-------------------------+----------+---------------+-----------------------------------------+
| FUSION                  | FUSION   | Fusion        |                                    5575 |
| MUTATION_EXTENDED       |          | Fusion        |                                     314 |
| MUTATION_EXTENDED       | FUSION   | Fusion        |                                    5334 |
| MUTATION_EXTENDED       | MAF      | Fusion        |                                  253393 |
+-------------------------+----------+---------------+-----------------------------------------+
4 rows in set (0.81 sec)
`

cbioportal-public-db.cq26ederqvxp.us-east-1.rds.amazonaws.com cgds_public_hgnc:

`
mysql> select genetic_profile.GENETIC_ALTERATION_TYPE, genetic_profile.DATATYPE, mutation_event.MUTATION_TYPE, count(mutation_event.MUTATION_EVENT_ID) from mutation_event, mutation, genetic_profile where genetic_profile.GENETIC_PROFILE_ID=mutation.GENETIC_PROFILE_ID and mutation.MUTATION_EVENT_ID=mutation_event.MUTATION_EVENT_ID and mutation_event.MUTATION_TYPE="Fusion" group by genetic_profile.GENETIC_ALTERATION_TYPE, genetic_profile.DATATYPE, mutation_event.MUTATION_TYPE;
+-------------------------+----------+---------------+-----------------------------------------+
| GENETIC_ALTERATION_TYPE | DATATYPE | MUTATION_TYPE | count(mutation_event.MUTATION_EVENT_ID) |
+-------------------------+----------+---------------+-----------------------------------------+
| MUTATION_EXTENDED       | MAF      | Fusion        |                                  105056 |
+-------------------------+----------+---------------+-----------------------------------------+
1 row in set (0.53 sec)

`

Almost all fusion mutations are from MUTATION_EXTENDED MAF records, so focus on this.  Are the fusion/fusion and Mutation extended/"" old studies?

**Comment by mandawilson** [comment]
How many "FUSION" vs "STRUCTURAL_VARIANT" genetic_profile.GENETIC_ALTERATION_TYPE do we have?

`select
    genetic_profile.GENETIC_ALTERATION_TYPE,
    genetic_profile.DATATYPE,
    count(GENETIC_PROFILE_ID)
    from    
        genetic_profile
    where
    (genetic_profile.genetic_alteration_type="STRUCTURAL_VARIANT" or
        genetic_profile.genetic_alteration_type="FUSION")
    group by genetic_profile.GENETIC_ALTERATION_TYPE,
    genetic_profile.DATATYPE;`

`+-------------------------+----------+---------------------------+
| GENETIC_ALTERATION_TYPE | DATATYPE | count(GENETIC_PROFILE_ID) |
+-------------------------+----------+---------------------------+
| FUSION                  | FUSION   |                         9 |
| STRUCTURAL_VARIANT      | FUSION   |                       482 |
+-------------------------+----------+---------------------------+
2 rows in set (0.00 sec)`

**Comment by mandawilson** [comment]
mysql> select cancer_study.CANCER_STUDY_IDENTIFIER, mutation.*, mutation_event.* from mutation_event, mutation, genetic_profile, sample, patient, cancer_study where  genetic_profile.GENETIC_PROFILE_ID=mutation.GENETIC_PROFILE_ID and mutation.MUTATION_EVENT_ID=mutation_event.MUTATION_EVENT_ID and mutation_event.MUTATION_TYPE="Fusion" and GENETIC_ALTERATION_TYPE="MUTATION_EXTENDED" and DATATYPE="MAF" and sample.INTERNAL_ID=mutation.SAMPLE_ID and patient.INTERNAL_ID=sample.PATIENT_ID and patient.CANCER_STUDY_ID=cancer_study.CANCER_STUDY_ID and cancer_study.CANCER_STUDY_IDENTIFIER="msk_impact_2017" limit 1\G
*************************** 1. row ***************************
      CANCER_STUDY_IDENTIFIER: msk_impact_2017
            MUTATION_EVENT_ID: 31210836
           GENETIC_PROFILE_ID: 59710
                    SAMPLE_ID: 93477280
               ENTREZ_GENE_ID: -351
                       CENTER: MSKCC-DMP
                    SEQUENCER: NA
              MUTATION_STATUS: NA
            VALIDATION_STATUS: NA
            TUMOR_SEQ_ALLELE1: NA
            TUMOR_SEQ_ALLELE2: NA
  MATCHED_NORM_SAMPLE_BARCODE: NA
       MATCH_NORM_SEQ_ALLELE1: NA
       MATCH_NORM_SEQ_ALLELE2: NA
     TUMOR_VALIDATION_ALLELE1: NA
     TUMOR_VALIDATION_ALLELE2: NA
MATCH_NORM_VALIDATION_ALLELE1: NA
MATCH_NORM_VALIDATION_ALLELE2: NA
          VERIFICATION_STATUS: NA
             SEQUENCING_PHASE: NA
              SEQUENCE_SOURCE: NA
            VALIDATION_METHOD: NA
                        SCORE: NA
                     BAM_FILE: NA
              TUMOR_ALT_COUNT: -1
              TUMOR_REF_COUNT: -1
             NORMAL_ALT_COUNT: -1
             NORMAL_REF_COUNT: -1
            AMINO_ACID_CHANGE: NULL
              ANNOTATION_JSON: NULL
            MUTATION_EVENT_ID: 31210836
               ENTREZ_GENE_ID: -351
                          CHR: NA
               START_POSITION: -1
                 END_POSITION: -1
             REFERENCE_ALLELE: NA
             TUMOR_SEQ_ALLELE: 
               PROTEIN_CHANGE: ARID1A-MIR1976 fusion
                MUTATION_TYPE: Fusion
      FUNCTIONAL_IMPACT_SCORE: NA
                    FIS_VALUE: -1
                    LINK_XVAR: NA
                     LINK_PDB: NA
                     LINK_MSA: NA
                   NCBI_BUILD: NA
                       STRAND: NA
                 VARIANT_TYPE: NA
                    DB_SNP_RS: NA
            DB_SNP_VAL_STATUS: NA
           ONCOTATOR_DBSNP_RS: NA
     ONCOTATOR_REFSEQ_MRNA_ID: NA
       ONCOTATOR_CODON_CHANGE: NA
 ONCOTATOR_UNIPROT_ENTRY_NAME: NA
  ONCOTATOR_UNIPROT_ACCESSION: NA
  ONCOTATOR_PROTEIN_POS_START: -1
    ONCOTATOR_PROTEIN_POS_END: -1
         CANONICAL_TRANSCRIPT: 1
                      KEYWORD: MIR-1976/1976 ARID1A-MIR1976 fusion
1 row in set (9.26 sec)

mysql> select * from gene where ENTREZ_GENE_ID=-351;
+----------------+------------------+-------------------+-------+
| ENTREZ_GENE_ID | HUGO_GENE_SYMBOL | GENETIC_ENTITY_ID | TYPE  |
+----------------+------------------+-------------------+-------+
|           -351 | MIR-1976/1976    |             36223 | miRNA |
+----------------+------------------+-------------------+-------+
1 row in set (0.00 sec)



*************************** 1. row ***************************
      CANCER_STUDY_IDENTIFIER: msk_impact_2017
            MUTATION_EVENT_ID: 3428638
           GENETIC_PROFILE_ID: 3397
                    SAMPLE_ID: 296611
               ENTREZ_GENE_ID: 7113
                       CENTER: MSKCC-DMP
                    SEQUENCER: NA
              MUTATION_STATUS: NA
            VALIDATION_STATUS: NA
            TUMOR_SEQ_ALLELE1: NA
            TUMOR_SEQ_ALLELE2: NA
  MATCHED_NORM_SAMPLE_BARCODE: NA
       MATCH_NORM_SEQ_ALLELE1: NA
       MATCH_NORM_SEQ_ALLELE2: NA
     TUMOR_VALIDATION_ALLELE1: NA
     TUMOR_VALIDATION_ALLELE2: NA
MATCH_NORM_VALIDATION_ALLELE1: NA
MATCH_NORM_VALIDATION_ALLELE2: NA
          VERIFICATION_STATUS: NA
             SEQUENCING_PHASE: NA
              SEQUENCE_SOURCE: NA
            VALIDATION_METHOD: NA
                        SCORE: NA
                     BAM_FILE: NA
              TUMOR_ALT_COUNT: -1
              TUMOR_REF_COUNT: -1
             NORMAL_ALT_COUNT: -1
             NORMAL_REF_COUNT: -1
            AMINO_ACID_CHANGE: NULL
              ANNOTATION_JSON: NULL
            MUTATION_EVENT_ID: 3428638
               ENTREZ_GENE_ID: 7113
                          CHR: NA
               START_POSITION: -1
                 END_POSITION: -1
             REFERENCE_ALLELE: NA
             TUMOR_SEQ_ALLELE: 
               PROTEIN_CHANGE: TMPRSS2-ERG fusion
                MUTATION_TYPE: Fusion
      FUNCTIONAL_IMPACT_SCORE: NA
                    FIS_VALUE: -1
                    LINK_XVAR: NA
                     LINK_PDB: NA
                     LINK_MSA: NA
                   NCBI_BUILD: NA
                       STRAND: NA
                 VARIANT_TYPE: NA
                    DB_SNP_RS: NA
            DB_SNP_VAL_STATUS: NA
           ONCOTATOR_DBSNP_RS: NA
     ONCOTATOR_REFSEQ_MRNA_ID: NA
       ONCOTATOR_CODON_CHANGE: NA
 ONCOTATOR_UNIPROT_ENTRY_NAME: NA
  ONCOTATOR_UNIPROT_ACCESSION: NA
  ONCOTATOR_PROTEIN_POS_START: -1
    ONCOTATOR_PROTEIN_POS_END: -1
         CANONICAL_TRANSCRIPT: 1
                      KEYWORD: TMPRSS2 TMPRSS2-ERG fusion
1 row in set (40.00 sec)

mysql> select cancer_study.CANCER_STUDY_IDENTIFIER, mutation.*, mutation_event.* from mutation_event, mutation, genetic_profile, sample, patient, cancer_study where  genetic_profile.GENETIC_PROFILE_ID=mutation.GENETIC_PROFILE_ID and mutation.MUTATION_EVENT_ID=mutation_event.MUTATION_EVENT_ID and mutation_event.MUTATION_TYPE="Fusion" and GENETIC_ALTERATION_TYPE="MUTATION_EXTENDED" and DATATYPE="MAF" and sample.INTERNAL_ID=mutation.SAMPLE_ID and patient.INTERNAL_ID=sample.PATIENT_ID and patient.CANCER_STUDY_ID=cancer_study.CANCER_STUDY_ID and cancer_study.CANCER_STUDY_IDENTIFIER<>"msk_impact_2017" ORDER BY mutation_event.MUTATION_EVENT_ID  limit 1\G
*************************** 1. row ***************************
      CANCER_STUDY_IDENTIFIER: coadread_tcga_pan_can_atlas_2018
            MUTATION_EVENT_ID: 257727
           GENETIC_PROFILE_ID: 5594
                    SAMPLE_ID: 521672
               ENTREZ_GENE_ID: 2140
                       CENTER: WashU
                    SEQUENCER: NA
              MUTATION_STATUS: NA
            VALIDATION_STATUS: NA
            TUMOR_SEQ_ALLELE1: NA
            TUMOR_SEQ_ALLELE2: NA
  MATCHED_NORM_SAMPLE_BARCODE: NA
       MATCH_NORM_SEQ_ALLELE1: NA
       MATCH_NORM_SEQ_ALLELE2: NA
     TUMOR_VALIDATION_ALLELE1: NA
     TUMOR_VALIDATION_ALLELE2: NA
MATCH_NORM_VALIDATION_ALLELE1: NA
MATCH_NORM_VALIDATION_ALLELE2: NA
          VERIFICATION_STATUS: NA
             SEQUENCING_PHASE: NA
              SEQUENCE_SOURCE: NA
            VALIDATION_METHOD: NA
                        SCORE: NA
                     BAM_FILE: NA
              TUMOR_ALT_COUNT: -1
              TUMOR_REF_COUNT: -1
             NORMAL_ALT_COUNT: -1
             NORMAL_REF_COUNT: -1
            AMINO_ACID_CHANGE: NULL
              ANNOTATION_JSON: NULL
            MUTATION_EVENT_ID: 257727
               ENTREZ_GENE_ID: 2140
                          CHR: NA
               START_POSITION: -1
                 END_POSITION: -1
             REFERENCE_ALLELE: NA
             TUMOR_SEQ_ALLELE: 
               PROTEIN_CHANGE: EYA3-GUCA1C
                MUTATION_TYPE: Fusion
      FUNCTIONAL_IMPACT_SCORE: NA
                    FIS_VALUE: -1
                    LINK_XVAR: NA
                     LINK_PDB: NA
                     LINK_MSA: NA
                   NCBI_BUILD: NA
                       STRAND: NA
                 VARIANT_TYPE: NA
                    DB_SNP_RS: NA
            DB_SNP_VAL_STATUS: NA
           ONCOTATOR_DBSNP_RS: NA
     ONCOTATOR_REFSEQ_MRNA_ID: NA
       ONCOTATOR_CODON_CHANGE: NA
 ONCOTATOR_UNIPROT_ENTRY_NAME: NA
  ONCOTATOR_UNIPROT_ACCESSION: NA
  ONCOTATOR_PROTEIN_POS_START: -1
    ONCOTATOR_PROTEIN_POS_END: -1
         CANONICAL_TRANSCRIPT: 1
                      KEYWORD: EYA3 EYA3-GUCA1C
1 row in set (39.35 sec)

FUSION datatype:
mysql> select cancer_study.CANCER_STUDY_IDENTIFIER, mutation.*, mutation_event.* from mutation_event, mutation, genetic_profile, sample, patient, cancer_study where  genetic_profile.GENETIC_PROFILE_ID=mutation.GENETIC_PROFILE_ID and mutation.MUTATION_EVENT_ID=mutation_event.MUTATION_EVENT_ID and mutation_event.MUTATION_TYPE="Fusion" and GENETIC_ALTERATION_TYPE="MUTATION_EXTENDED" and DATATYPE="FUSION" and sample.INTERNAL_ID=mutation.SAMPLE_ID and patient.INTERNAL_ID=sample.PATIENT_ID and patient.CANCER_STUDY_ID=cancer_study.CANCER_STUDY_ID limit 1\G
*************************** 1. row ***************************
      CANCER_STUDY_IDENTIFIER: mskarcher
            MUTATION_EVENT_ID: 20179655
           GENETIC_PROFILE_ID: 87251
                    SAMPLE_ID: 166670051
               ENTREZ_GENE_ID: 238
                       CENTER: MSKCC-DMP
                    SEQUENCER: NA
              MUTATION_STATUS: NA
            VALIDATION_STATUS: NA
            TUMOR_SEQ_ALLELE1: NA
            TUMOR_SEQ_ALLELE2: NA
  MATCHED_NORM_SAMPLE_BARCODE: NA
       MATCH_NORM_SEQ_ALLELE1: NA
       MATCH_NORM_SEQ_ALLELE2: NA
     TUMOR_VALIDATION_ALLELE1: NA
     TUMOR_VALIDATION_ALLELE2: NA
MATCH_NORM_VALIDATION_ALLELE1: NA
MATCH_NORM_VALIDATION_ALLELE2: NA
          VERIFICATION_STATUS: NA
             SEQUENCING_PHASE: NA
              SEQUENCE_SOURCE: NA
            VALIDATION_METHOD: NA
                        SCORE: NA
                     BAM_FILE: NA
              TUMOR_ALT_COUNT: -1
              TUMOR_REF_COUNT: -1
             NORMAL_ALT_COUNT: -1
             NORMAL_REF_COUNT: -1
            AMINO_ACID_CHANGE: NULL
              ANNOTATION_JSON: NULL
            MUTATION_EVENT_ID: 20179655
               ENTREZ_GENE_ID: 238
                          CHR: NA
               START_POSITION: -1
                 END_POSITION: -1
             REFERENCE_ALLELE: NA
             TUMOR_SEQ_ALLELE: 
               PROTEIN_CHANGE: ALK-EML4 fusion
                MUTATION_TYPE: Fusion
      FUNCTIONAL_IMPACT_SCORE: NA
                    FIS_VALUE: -1
                    LINK_XVAR: NA
                     LINK_PDB: NA
                     LINK_MSA: NA
                   NCBI_BUILD: NA
                       STRAND: NA
                 VARIANT_TYPE: NA
                    DB_SNP_RS: NA
            DB_SNP_VAL_STATUS: NA
           ONCOTATOR_DBSNP_RS: NA
     ONCOTATOR_REFSEQ_MRNA_ID: NA
       ONCOTATOR_CODON_CHANGE: NA
 ONCOTATOR_UNIPROT_ENTRY_NAME: NA
  ONCOTATOR_UNIPROT_ACCESSION: NA
  ONCOTATOR_PROTEIN_POS_START: -1
    ONCOTATOR_PROTEIN_POS_END: -1
         CANONICAL_TRANSCRIPT: 1
                      KEYWORD: ALK ALK-EML4 fusion
1 row in set (0.00 sec)

empty string datatype:

mysql> select cancer_study.CANCER_STUDY_IDENTIFIER, mutation.*, mutation_event.* from mutation_event, mutation, genetic_profile, sample, patient, cancer_study where  genetic_profile.GENETIC_PROFILE_ID=mutation.GENETIC_PROFILE_ID and mutation.MUTATION_EVENT_ID=mutation_event.MUTATION_EVENT_ID and mutation_event.MUTATION_TYPE="Fusion" and GENETIC_ALTERATION_TYPE="MUTATION_EXTENDED" and DATATYPE="" and sample.INTERNAL_ID=mutation.SAMPLE_ID and patient.INTERNAL_ID=sample.PATIENT_ID and patient.CANCER_STUDY_ID=cancer_study.CANCER_STUDY_ID limit 1\G
*************************** 1. row ***************************
      CANCER_STUDY_IDENTIFIER: dlbc_13-081_mskcc_foundation
            MUTATION_EVENT_ID: 1446184
           GENETIC_PROFILE_ID: 1947
                    SAMPLE_ID: 141085
               ENTREZ_GENE_ID: 3492
                       CENTER: MSKCC
                    SEQUENCER: NA
              MUTATION_STATUS: NA
            VALIDATION_STATUS: NA
            TUMOR_SEQ_ALLELE1: NA
            TUMOR_SEQ_ALLELE2: NA
  MATCHED_NORM_SAMPLE_BARCODE: NA
       MATCH_NORM_SEQ_ALLELE1: NA
       MATCH_NORM_SEQ_ALLELE2: NA
     TUMOR_VALIDATION_ALLELE1: NA
     TUMOR_VALIDATION_ALLELE2: NA
MATCH_NORM_VALIDATION_ALLELE1: NA
MATCH_NORM_VALIDATION_ALLELE2: NA
          VERIFICATION_STATUS: NA
             SEQUENCING_PHASE: NA
              SEQUENCE_SOURCE: NA
            VALIDATION_METHOD: NA
                        SCORE: NA
                     BAM_FILE: NA
              TUMOR_ALT_COUNT: NULL
              TUMOR_REF_COUNT: NULL
             NORMAL_ALT_COUNT: NULL
             NORMAL_REF_COUNT: NULL
            AMINO_ACID_CHANGE: NULL
              ANNOTATION_JSON: NULL
            MUTATION_EVENT_ID: 1446184
               ENTREZ_GENE_ID: 3492
                          CHR: NA
               START_POSITION: -1
                 END_POSITION: -1
             REFERENCE_ALLELE: NA
             TUMOR_SEQ_ALLELE: NA
               PROTEIN_CHANGE: IGH-BCL6 fusion
                MUTATION_TYPE: Fusion
      FUNCTIONAL_IMPACT_SCORE: NA
                    FIS_VALUE: -1
                    LINK_XVAR: NA
                     LINK_PDB: NA
                     LINK_MSA: NA
                   NCBI_BUILD: NA
                       STRAND: NA
                 VARIANT_TYPE: NA
                    DB_SNP_RS: NA
            DB_SNP_VAL_STATUS: NA
           ONCOTATOR_DBSNP_RS: NA
     ONCOTATOR_REFSEQ_MRNA_ID: NA
       ONCOTATOR_CODON_CHANGE: NA
 ONCOTATOR_UNIPROT_ENTRY_NAME: NA
  ONCOTATOR_UNIPROT_ACCESSION: NA
  ONCOTATOR_PROTEIN_POS_START: -1
    ONCOTATOR_PROTEIN_POS_END: -1
         CANONICAL_TRANSCRIPT: 1
                      KEYWORD: IGH IGH-BCL6 fusion
1 row in set (0.00 sec)

**Comment by mandawilson** [comment]
- [ ] Change/add record in sample_profile.  Do we assume every sample profiled for mutations was profiled for structural variants?
mysql> desc sample_profile;
+--------------------+---------+------+-----+---------+-------+
| Field              | Type    | Null | Key | Default | Extra |
+--------------------+---------+------+-----+---------+-------+
| SAMPLE_ID          | int(11) | NO   | PRI | NULL    |       |
| GENETIC_PROFILE_ID | int(11) | NO   | PRI | NULL    |       |
| PANEL_ID           | int(11) | YES  | MUL | NULL    |       |
+--------------------+---------+------+-----+---------+-------+
3 rows in set (0.00 sec)

**Comment by mandawilson** [comment]
- [ ] IMPORTANT: we need a gene panel for every sample_profile record we have to create.  Or rather if there is a gene panel for that gene for the sample profiled for something else like mutations it also has to have a gene panel for SVs. See: https://app.zenhub.com/workspaces/pipelines-scrum-5df2abb7846c01d560c42983/issues/knowledgesystems/pipelines-scrum/833 and https://app.zenhub.com/workspaces/pipelines-scrum-5df2abb7846c01d560c42983/issues/knowledgesystems/pipelines-scrum/832

**Comment by mandawilson** [comment]
Example SV:

mysql> select * from cgds_triage.structural_variant limit 1\G
*************************** 1. row ***************************
                 INTERNAL_ID: 1
          GENETIC_PROFILE_ID: 17166
                   SAMPLE_ID: 10229426
        SITE1_ENTREZ_GENE_ID: 6098
 SITE1_ENSEMBL_TRANSCRIPT_ID: NA
            SITE1_CHROMOSOME: 6
              SITE1_POSITION: 117662374
           SITE1_DESCRIPTION: Exon 30 of ROS1(-)
        SITE2_ENTREZ_GENE_ID: 10568
 SITE2_ENSEMBL_TRANSCRIPT_ID: NA
            SITE2_CHROMOSOME: 4
              SITE2_POSITION: 25667150
           SITE2_DESCRIPTION: Intron of SLC34A2(+): 600bp before exon 5
       SITE2_EFFECT_ON_FRAME: NA
                  NCBI_BUILD: GRCh37
                 DNA_SUPPORT: Yes
                 RNA_SUPPORT: NA
           NORMAL_READ_COUNT: 0
            TUMOR_READ_COUNT: 0
        NORMAL_VARIANT_COUNT: 0
         TUMOR_VARIANT_COUNT: 0
NORMAL_PAIRED_END_READ_COUNT: 6
 TUMOR_PAIRED_END_READ_COUNT: -1
     NORMAL_SPLIT_READ_COUNT: 17
      TUMOR_SPLIT_READ_COUNT: -1
                  ANNOTATION: NA
             BREAKPOINT_TYPE: FFPE-PooledNormal_bc
             CONNECTION_TYPE: 5to3
                  EVENT_INFO: Antisense fusion
                       CLASS: TRANSLOCATION
                      LENGTH: -1
                    COMMENTS: NA
                   SV_STATUS: SOMATIC
                site1_contig: NA
                site2_contig: NA
                site2_region: Intron
                site1_region: Exon
         site1_region_number: -1
         site2_region_number: -1
1 row in set (0.00 sec)

**Comment by mandawilson** [comment]
Get tabbed output from MySQL: 

https://dev.mysql.com/doc/mysql-shell/8.0/en/mysql-shell-output-tab-format.html

**Comment by mandawilson** [comment]
[wilson@ip-10-1-141-114 ~]$ mysql -u root -p cgds_gdac < fusion_queries.sql > fusion_query_results.txt

**Comment by mandawilson** [comment]
select PROTEIN_CHANGE, KEYWORD  from mutation_event where MUTATION_TYPE='Fusion' group by PROTEIN_CHANGE, KEYWORD;

**Comment by mandawilson** [comment]
-- gene not found in protein change, is it an alias?
select HUGO_GENE_SYMBOL, PROTEIN_CHANGE, KEYWORD, LOCATE(HUGO_GENE_SYMBOL, PROTEIN_CHANGE) AS GENE_POS
    from mutation_event, gene
    where MUTATION_TYPE='Fusion'
        and gene.ENTREZ_GENE_ID=mutation_event.ENTREZ_GENE_ID
        and LOCATE(HUGO_GENE_SYMBOL, PROTEIN_CHANGE) = 0;

e.g. | RAB29            | RAB7L1-FGFR2 fusion                                                                                                                               | RAB29 R

mysql> select * from gene_alias where ENTREZ_GENE_ID=8934;
+----------------+------------+
| ENTREZ_GENE_ID | GENE_ALIAS |
+----------------+------------+
|           8934 | RAB7L      |
|           8934 | RAB7L1     |
+----------------+------------+
2 rows in set (0.01 sec)
