### ISSUE TITLE
Setup New Repo for HGNC

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#825]
## Client (Who is making the request)
Yichao
## Issue/Deliverable
HGNC pulls from separate data repo under `/data/test-cbio-portal-data`
set PORTAL_HOME inside hgnc script

repo & fork https://github.com/cbioportal-curation-gene-update/datahub.git

**Comment by sheridancbio** [comment]
I have cloned https://github.com/cbioportal-curation-gene-update/datahub.git into the path /data/portal-cron/hgnc-portal-data/datahub on pipelines3

**Comment by sheridancbio** [comment]
in the hgnc importer.properties file, property importer.google.service.private.key.file points to $PORTAL_DATA_HOME/portal-configuration/google-docs .. so I have rsynced portal-configuration into hgnc-portal-data too

**Comment by sheridancbio** [comment]
The importer_configuration spreadsheet data_sources sheet makes reference to PORTAL_DATA_HOME in DOWNLOAD_DIRECTORY. It is expected that setting this environment variable appropriately for the hgnc importer will result in the correct copy of datahub being updated.

**Comment by sheridancbio** [comment]
data source fetch and study import were tested and seem to be working fine.
