### ISSUE TITLE
Debug Fusion Molecular Profile Counts in mskimpact

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#837]

**Comment by mandawilson** [comment]
https://cbioportal.mskcc.org/api/molecular-profile-sample-counts/fetch

[{
    "label": "Fusions",
    "value": "fusion",
    "count": 15431
}, {
    "label": "Mutations",
    "value": "mutations",
    "count": 83451
}, {
    "label": "Copy Number Alterations (MSK-IMPACT, HEME)",
    "value": "cna",
    "count": 83451
}]

./web/src/main/java/org/cbioportal/web/StudyViewController.java fetchMolecularProfileSampleCounts() -> cacheableFetchMolecularProfileSampleCounts() 
-> List<GenomicDataCount> genomicDataCounts = studyViewService.getGenomicDataCounts(studyIds, sampleIds);
./service/src/main/java/org/cbioportal/service/impl/StudyViewServiceImpl.java
-> genePanelService.fetchGenePanelDataInMultipleMolecularProfiles

-> genePanelService
            .fetchGenePanelDataInMultipleMolecularProfiles(molecularProfileSampleIdentifiers)
-> ./service/src/main/java/org/cbioportal/service/impl/GenePanelServiceImpl.java -> getGenePanelData()
-> fetchGenePanelDataByMolecularProfileIds() 
Has:
`// replace fusion profile id with mutation, as all the fusions are in mutation table
        // and are imported with mutation profile id
        // TODO: remove replacing logic once the fusions are migrated to structural variant in database
        Set<String> uniqueMolecularProfileIds = molecularProfiles
            .stream()
            .map(profile -> molecularProfileUtil.replaceFusionProfileWithMutationProfile(profile.getStableId()))
            .collect(toSet());`

./service/src/main/java/org/cbioportal/service/util/MolecularProfileUtil.java -> replaceFusionProfileWithMutationProfile()

-> molecularProfileUtil.categorizeMolecularProfilesByStableIdSuffixes - just removes CANCER_STUDY_INDENTIFIER + "_" from the identifier leaving the genetic profile

**Comment by averyniceday** [comment]
spreadsheet was altered to generate case lists for data_fusions -- this is probably doing something wacky but basically generating a case lists off of data_fusions.txt -- db has a `mskimpact_fusion` case list and a `msk_impact_2017_fusion` case list that has the numbers we're observing. 

Public db does not ahve a fusion case list
