### ISSUE TITLE
Convert Tests off Jenkins

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#859]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
- [ ] `mvn clean install` tests - this can be added as a simple .circleci/test file
- [ ] integration tests - switch to running in cron and add a Slack notification (?) - data checks against redcap
- [ ] oncotree data check - just have a oneline script that curations can run -- but maybe have a check that ensures a quality report uploaded (at your discretion) 

Lists of all tests are
dashi-dev port 8090

**Comment by mandawilson** [comment]
- [x] cbioportal - this is already running
- [ ] cdd-integration-test (in progress: decide where this will be run)
- [x] clinical-data-dictionary
- [x] cmo-pipelines
- [ ] fetcher-redcap-schema-integration-test (this needs genome-nexus-annotation-pipeline, which needs pipelines,cmo-pipelines ... this is where I stopped)
- [x] genome-nexus-annotation-pipeline - already has circleci building it on PRs
- [ ] oncotree-integration-test (in progress: decide where this will be run)
- [x] pipelines
- [ ] redcap-id-mappings-integration-test

- [ ] pipelines: TODO in circleci config file change back to knowledgesystems and stay on master branch

- [ ] remove eks-prod-old /home/wilson/fetcher-redcap-schema-integration-test/pipelines-credentials/application-secure.properties

**Comment by mandawilson** [comment]
- [x] cmo-pipelines PR https://github.com/knowledgesystems/cmo-pipelines/pull/955
- [ ] clinical-data-dictionary PR https://github.com/cBioPortal/clinical-data-dictionary/pull/127
- [x] pipelines PR https://github.com/knowledgesystems/pipelines/pull/447
- [ ] oncotree integration tests (not finished - where do we run and how do we make sure they are run for PRs?) https://github.com/mandawilson/oncotree/tree/mv-integration-tests-off-jenkins
- [ ] cdd integration tests (not finished - where do we run and how do we make sure they are run for PRs?) https://github.com/mandawilson/clinical-data-dictionary/tree/circleci-project-setup

**Comment by averyniceday** [comment]
In home directory on 10.1.21.42 -- 

Questions regarding checking out different versions of multiple repos because of dependencies 
Can people run it independently? (will have to checkout different git-repos and build sequentially) 
- [ ] who runs which tests, knowledge/skill level

**Comment by averyniceday** [comment]
Discussed with Ben, splitting out integration tests -- data check independent of rest of tests

**Comment by mandawilson** [comment]
Maybe only remove post-build Github actions where I say "remove".

- [ ] cbioportal - remove
- [ ] cdd-integration-test - keep, this has all it needs already
- [ ] clinical-data-dictionary - remove
- [ ] cmo-pipelines - remove
- [ ] fetcher-redcap-schema-integration-test - this copies artifacts from the pipelines project
- [ ] genome-nexus-annotation-pipeline - remove
- [ ] oncotree-integration-test - keep - this doesn't copy anything but it builds multiple projects
- [ ] pipelines - triggers builds of cmo-pipelines, genome-nexus-annotation-pipeline?
- [ ] redcap-id-mappings-integration-test - keep


- [ ] pipelines: TODO in circleci config file change back to knowledgesystems and stay on master branch

- [ ] remove eks-prod-old /home/wilson/fetcher-redcap-schema-integration-test/pipelines-credentials/application-secure.properties
