### ISSUE TITLE
Have Backend Approval for SV PR

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#876]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Sit down with Rob and go through the entire rebased PR to get final approval

cbioportal PR: 
https://github.com/cBioPortal/cbioportal/pull/9459

cmo-pipelines PR: 
https://github.com/knowledgesystems/cmo-pipelines/pull/929
https://github.com/knowledgesystems/cmo-pipelines/pull/931

pipelines PR:
https://github.com/knowledgesystems/pipelines/pull/445 

fallback image: `sv-public-push`
current image: `sv-public-push-v2.0`

GNAP hash for building importer: `1b2a3675636f3c1a552e53d0584e4d3bd59a7a68`
Deployed as HGNC Importer

**Comment by sheridancbio** [comment]
The code currently looks good, but requires updates to the documentation (FileFormats) and to the python validator before it can be approved/merged. Notes are added to the PR in comments.
