### ISSUE TITLE
Test and Compile List of Problematic Endpoints with Sample List Issue

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#887]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Identify all endpoints that can take in an arbitrary number of samples

**Comment by averyniceday** [comment]
https://docs.google.com/document/d/1YiawE93A3A6x7wwnKtQidF912WXLAjdSnByvFGfULkQ/edit?usp=sharing

**Comment by sheridancbio** [comment]
I have added a second section to the google doc above, based on examination of the java code (controllers mostly). This covered the original 22 reported endpoints, and adds 8 additional endpoints of concern. It also lists the details of the study view endpoints which have long lists of sample/patient ids (13 endpoints)
