### ISSUE TITLE
Integrate Publisher into Overnight Pipeline

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#899]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
NATs server publishing samples from MPath needs to work within the context of our overnight pipelines. This includes ensuring "consumed" and published samples do not disrupt the master list of samples our data fetchers. 

## Technical Description (How are we going to achieve the above)
This is also left up to the fellow but should be designed in conjunction with the cBioPortal pipelines team. Important questions to answer include: Which API should samples be sourced from? How will samples be consumed for both the publisher and CVR fetcher? How will samples be handed off between the two components? Potentially have subscriber write out a JSON file for CVR fetcher to use.

![Screen Shot 2022-06-01 at 8.07.44 AM.png](https://images.zenhubusercontent.com/5df39fc0f51fae8b1f448ec0/9cc50552-175b-42df-8b90-ac2943e5565b)

We'll be focusing on the publisher and how it interacts with the JSON it receives from CVR (the upstream system)
- [ ] Look into Mongo and its API for built in functionality for supporting record updates
- [ ] We need business logic that can parse the JSON and determine for each sample whether its a new sample or updated sample (and saved accordingly)
- [ ] updated and new samples should be published to separate channels

on the side, I will also look into adding a package for sending requests to CVR API - so that instead of passing in one JSON file we automatically read it from their response.

AFTERWARDS we will focus on the subscriber --
Subscriber will receive info from the publisher (one sample at a time) and (?) write out to a master JSON that gets processed overnight. 

Interactions with Mongo will be in its own package.
Business logic for parsing JSON, determining new/updated samples are in its own package. 

## Potential Issues
CVR team might need to create a separate endpoint OR backend pipeline team will need to make additional code changes as part of the solution. May introduce some complexity. 

Need to get more familiar with the JSON structure - one sample has multiple events associated with it - how does this look once stored inside Mongo

**Comment by n1zea144** [comment]
Some questions:
* Do we engineer independently of the existing cBioPortal ETL?
* Is this the sole consumer of CVR samples?
* How do we handle requeing of samples that have failed import into cBioPortal database?
* Can we do this without moving the existing cBioPortal ETL to an event-driven realtime model? (consumer drops cvr json at a predefined location for cvr fetcher to process? )
