### ISSUE TITLE
Debug CVR, DDP Failed Fetches

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#914]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
CVR/DDP failed over the weekend

**Comment by sheridancbio** [comment]
the heme cvr queue had approximately 1200 samples in it, causing out of memory failures during import runs. Samples were manually consumed to reduce the total number which came down. The cbio_retrieve_heme_variants endpoint limits delivery to 1000 samples, so it took multiple consumptions to clear the queue.

Attempts to do a cvr fetch also failed with 640 samples in the queue, and with 320 samples in the queue (which stalled for 10 hours during the fetch and using a customized import script which only fetched heme samples. So the first successful batch to be fetched was 132 samples.

**Comment by sheridancbio** [comment]
Manual consumptions to trim down the queue initially were in sizes: 498, 343, 175 .. tracked in these files on the aws pipelines node:
  498 current_heme_consume.ids.5_16_1
  343 current_heme_consume.ids.5_17_1
  175 current_heme_consume.ids.5_17_2

Then after each successful fetch operation, the successfully fetch samples were consumed manually (if needed), and then the next batch were requeued. An aggregate list of samples which had been manually cleared was maintained.

**Comment by sheridancbio** [comment]
The manual heme requeueing process needed to be repeated for 1000+ samples which were queued in the access pipeline. 4 batches of 250 samples were run through the importer with manual requeueing / consumption in two full imports and two extra fetches on May 21/22.
