### ISSUE TITLE
Migrate Mongo for Genome Nexus

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#915]

**Comment by mandawilson** [comment]
The dumps of gnap genome nexus in public haven’t been working since Sept 2020.  That is the last time the file was updated when you look at the S3 bucket.  Here is what this command shows kubectl logs -n genome-nexus gnap-genome-nexus-mongodump-cronjob-1656806400-2nb2p

```
Done dumping database


Compressing mongo dump
tar: Removing leading `/' from member names
/gnap-mongodump/
/gnap-mongodump/lost+found/
Done compressing mongo dump


Move the data to s3

An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
Done moving the database dump


Update contents of latest_mongo_dump.txt

An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.
Done updating contents of latest_mongo_dump.txt
```

So also the script doesn’t alert anyone to the failure.

**Comment by mandawilson** [comment]
Public:

MongoDB shell version v4.0.12
> show dbs 
admin       0.000GB
annotator  10.182GB
config      0.000GB
local       0.000GB
> db.annotator.count()
0
> use annotator
switched to db annotator
> show collections
clinvar.mutation
ensembl.biomart_transcripts
ensembl.canonical_transcript_per_hgnc
hotspot.mutation
mutation_assessor.annotation
my_variant_info.annotation
oncokb.gene
pfam.domain
ptm.experimental
signal.mutation
vep.annotation
> db.vep.annotation.count()
8897363

Copied dumped DB to pod:

kubectl cp /tmp/backup_07-06-2022-20-14-57.tar.gz genome-nexus/gnap-gn-mongo-mongodb-869cbbc6c5-7qpnt:/tmp

Then:
cd /tmp

Empty current mongo annotation db:
$ mongo
> show dbs
admin      0.000GB
annotator  0.719GB
config     0.000GB
local      0.000GB
> use annotator
switched to db annotator
> db.dropDatabase()
{ "dropped" : "annotator", "ok" : 1 }
> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
> exit

$ mongorestore dump

$ mongo
> show dbs
admin       0.000GB
annotator  10.390GB
config      0.000GB
local       0.000GB
> use annotator
switched to db annotator
> show collections
clinvar.mutation
ensembl.biomart_transcripts
ensembl.canonical_transcript_per_hgnc
hotspot.mutation
mutation_assessor.annotation
my_variant_info.annotation
oncokb.gene
pfam.domain
ptm.experimental
signal.mutation
vep.annotation
> db.vep.annotation.count()
8897527
