### ISSUE TITLE
Review cBioPortal PR to upgrade to Java 17

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#920]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
We answer the question - does this PR break our importers (any changes can be planned for next scrum)
https://github.com/cBioPortal/cbioportal/pull/9562

## Potential Issues
PR contains upgrade to Spring version

**Comment by averyniceday** [comment]
Known Issues
- local compiler version
- jitpack.yml needs to be added so jitpack will build with right java version (default is 8, we need 17)

Issues related to building with java17 and new hash (Genome Nexus)
- can't build genome nexus annotation pipeline with old spring version (2.3) - builds with 2.7 but not sure about additional issues that may come up
- Additional unknown errors:
```
java.net.URISyntaxException: Illegal character in path at index 61: file:/Users/wanga5/.m2/repository/batik/batik-rasterizer/1.5/\

java.net.URISyntaxException: Illegal character in path at index 50: file:/Users/wanga5/.m2/repository/batik/batik/1.5/\
```
- update junit?
```
WARNING: TestEngine with ID 'junit-vintage' failed to discover tests
org.junit.platform.commons.JUnitException: Failed to parse version of junit:junit: 4.13.2
```
- update spring framework + spring boot version
