### ISSUE TITLE
support oncoKB annotation of SV in mskimpact sources

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#922]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
our nightly oncokb-annotator run is annotating data_sv.txt with oncokb fields

## Technical Description (How are we going to achieve the above)
- [ ] update the oncokb-annotator version once Hongxin releases the updates into the oncokb server
- [ ] update our annotation and push scripts to use and commit the data_sv.txt results

**Comment by zhx828** [comment]
v3.3.0 was just released to support annotating SV https://github.com/oncokb/oncokb-annotator/releases It also introduces additional annotation columns, so in your pipeline, you might want to adjust based on the new output.

**Comment by zhx828** [comment]
I think we can close this ticket? @sheridancbio

**Comment by sheridancbio** [comment]
data_sv.oncokb.txt file apparently not being committed into github

**Comment by sheridancbio** [comment]
A bug in the annotation script has been corrected. The second line below was missing the dollar sign dereference operator in a few of the terms:
        echo "Beginning SV annotation..."
        $PYTHON3_BINARY $SV_ANNOTATOR_SCRIPT -b $ONCOKB_TOKEN -i $STAGING_SV_FILE -o $ONCOKB_SV_FILE -c $STAGING_SAMPLE_FILE

**Comment by sheridancbio** [comment]
the bug fix worked
