### ISSUE TITLE
Confirm Fusion Gene Orders for Archer

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#924]
data fusion file for archer has reversed gene names - TMPRSS2-ERG but saved as ERG-TMPRSS2

double check what this looks like in the SV file (if it's in the right order in SV file then it's okay and we can close it)

See if this is automatically done inside the CVR pipeline (or elsewhere in pipelines scripts?)

This is just to confirm and understand the source of the problem. Not to implement the fix

**Comment by mandawilson** [comment]
[cbioportal_importer@ip-10-1-141-114 mskarcher]$ cut -f 1,5 data_fusions.txt | grep TMPRSS2 | grep ERG
TMPRSS2	ERG-TMPRSS2 fusion
ERG	ERG-TMPRSS2 fusion
TMPRSS2	ERG-TMPRSS2 fusion
ERG	ERG-TMPRSS2 fusion
TMPRSS2	ERG-TMPRSS2 fusion
ERG	ERG-TMPRSS2 fusion
TMPRSS2	ERG-TMPRSS2 fusion
ERG	ERG-TMPRSS2 fusion

**Comment by mandawilson** [comment]
[cbioportal_importer@ip-10-1-141-114 mskarcher]$ grep TMPRSS2 data_SV.txt | grep ERG| cut -f 15,19
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG
TMPRSS2	ERG

**Comment by mandawilson** [comment]
In cvr json 
      "annotation" : "POSITIVE FOR THE FOLLOWING GENE FUSION IN THE CLINICALLY VALIDATED PANEL:\n\nTMPRSS2-ERG fusion.\nNote: The rearrangement is an in-frame fusion between genes TMPRSS2 Exon1 (NM_005656) and ERG Exon2 (NM_182918).",
      "comments" : "Lab Notes\nRun Number: ArcherV2-CLIN-20170021\nMacro-dissection: Not Performed\n",
      "site1_gene" : "TMPRSS2",
      "site2_gene" : "ERG",
      "gene1" : "TMPRSS2",
      "gene2" : "ERG",

**Comment by mandawilson** [comment]
Anusha confirmed that it is correct in data_SV.txt
