### ISSUE TITLE
Convert SV Descriptions to use Structural Variants instead of SV for Molecular Profiles

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#925]
Update descriptions both in database (using global query) and google spreadsheet.
Descriptions should use "structural variants" instead of "sv".

**Comment by mandawilson** [comment]
I *think* it means this, which I did on what I call 'eks-prod-old', cgds_triage, and I also changed portal_importer_configuration_testing_sv_import -> datatypes -> META_PROFILE_NAME for structural-variant from "SV Data" to "Structural Variant Data" which is also already what the default description is.

What is the main database that needs updating?

mysql> select * from genetic_profile where genetic_alteration_type='STRUCTURAL_VARIANT';
+--------------------+-------------------------------------+-----------------+-------------------------+----------+-----------------------+-------------------------------------------+------------------------------+-----------------+------------+--------------------+---------------+
| GENETIC_PROFILE_ID | STABLE_ID                           | CANCER_STUDY_ID | GENETIC_ALTERATION_TYPE | DATATYPE | NAME                  | DESCRIPTION                               | SHOW_PROFILE_IN_ANALYSIS_TAB | PIVOT_THRESHOLD | SORT_ORDER | GENERIC_ASSAY_TYPE | PATIENT_LEVEL |
+--------------------+-------------------------------------+-----------------+-------------------------+----------+-----------------------+-------------------------------------------+------------------------------+-----------------+------------+--------------------+---------------+
|              17181 | msk_impact_2017_structural_variants |            4850 | STRUCTURAL_VARIANT      | SV       | mskimpact2017 SV Data | Structural Variant Data for mskimpact2017 |                            1 |            NULL | NULL       | NULL               |             0 |
|              17240 | acbc_mskcc_2015_structural_variants |            4874 | STRUCTURAL_VARIANT      | SV       | SV Data               | Structural Variant Data.                  |                            1 |            NULL | NULL       | NULL               |             0 |
|              17243 | all_stjude_2015_structural_variants |            4876 | STRUCTURAL_VARIANT      | SV       | SV Data               | Structural Variant Data.                  |                            1 |            NULL | NULL       | NULL               |             0 |
+--------------------+-------------------------------------+-----------------+-------------------------+----------+-----------------------+-------------------------------------------+------------------------------+-----------------+------------+--------------------+---------------+
3 rows in set (0.00 sec)

mysql> update genetic_profile set NAME='Structural variant data' where name='SV Data';

**Comment by mandawilson** [comment]
Avery: I think it's the description field that needs to be updated--but I would confirm with Ramya/Anusha. I'm sure it's related to something displayed on the frontend so would be to confirm whether it's coming from the Name or Description field - might be good for both. Once the query is worked out it'll need to be applied to
10.1.141.114
cgds_hgnc (current SV-ified public)
devdb (current SV-ified gdac)
For testing this can also applied to this db that's backing beta

https://beta.cbioportal.org/study/summary?id=laml_tcga_pub

**Comment by mandawilson** [comment]
Also sv_demodb2 for the public beta 

update genetic_profile set NAME='Structural variants' where name='Structural variant data';
