### ISSUE TITLE
Structural Variant "Class" default setting

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#926]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
We need to change the default setting for structural variant records that do not have a class from "NA" to "Structural Variant of Unknown Type" or "Variant of Unknown Type" if space is limited.

## Technical Description (How are we going to achieve the above)
The default VariantClass setting for SVs is set to "NA" which is ambiguous to the user.  Technically the samples have an SV, its just that the information was not given.  An example of this is below.

https://beta.cbioportal.org/results/plots?cancer_study_list=laml_tcga_pub&tab_index=tab_visualize&case_set_id=laml_tcga_pub_all&Action=Submit&gene_list=RARA%250APML%250AKMT2A%250AMYH11%250ACBFB%250ARUNX1&plots_horz_selection=%7B%22dataType%22%3A%22STRUCTURAL_VARIANT%22%7D&plots_vert_selection=%7B%7D&plots_coloring_selection=%7B%22colorBySv%22%3A%22true%22%7D

Address why value is coming back as VariantClass (in the JSON) when VariantClass is not a property of Structural Variants - check whether we are really disconnected from mutations
## Potential Issues
Its not clear where this setting is made .  We know the data file in the link above is not providing it.  Is NA set on import or when the data is being send out the controller?

**Comment by mandawilson** [comment]
alter table structural_variant modify CLASS varchar(100) DEFAULT "Structural Variant of Unknown Type";

**Comment by mandawilson** [comment]
vi ./core/src/main/java/org/mskcc/cbio/portal/util/StructuralVariantUtil.java
        structuralVariant.setDriverFilterAnn(TabDelimitedFileUtil.getPartString(getColumnIndex(StructuralVariantUtil.DRIVER_FILTER_ANNOTATION), parts));

**Comment by mandawilson** [comment]
- [ ] Add alter table code to schema + db upgrade sql
- [ ] Is variant class used somewhere else where making this change messes up another page (e.g. does another page want/expect it to be NA)?  In which case maybe the solution is to make it null/NA in the database and have the frontend change it to be the string it wants on this particular page.
