### ISSUE TITLE
Dremio Prototype Implementation and Evaluation

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#929]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)

- the Dremio prototype has been implemented according to plan
- the endpoint clinical-data-bin-counts produces equivalent output between the standard reference system and the prototype
- the performance has been evaluated and a summary of results and lessons learns is made

**Comment by sheridancbio** [comment]
Met with dremio team (Sarab) today and discussed the performance improvement goals and experience during the first round of prototyping

**Comment by sheridancbio** [comment]
It seems like if the prototype backend is not in use for an hour(?) we get a null pointer exception. Is this because there is some kind of maintained connection which gets corrupted?
</pre><p><b>Root Cause</b></p><pre>java.lang.NullPointerException
        java.base&#47;java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        java.base&#47;java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        java.base&#47;java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        java.base&#47;java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        java.base&#47;java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        java.base&#47;java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        java.base&#47;java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        org.cbioportal.web.util.ClinicalDataBinUtil.fetchClinicalDataBinCounts(ClinicalDataBinUtil.java:131)
        org.cbioportal.web.StudyViewController.cachableFetchClinicalDataBinCounts(StudyViewController.java:167)
        org.cbioportal.web.StudyViewController.fetchClinicalDataBinCounts(StudyViewController.java:153)


OK ... we discovered that restarting the backend pod corrected this. One note for the "Lessons Learned" document is that this problem must be avoided [this is a bug ... possibly in the example/tutorial code that came from Dremio ]

**Comment by sheridancbio** [comment]
When we reduce the number of fields in the reflection (output) the query became slower (compared to "select *").

**Comment by mandawilson** [comment]
Note: MySQL is not caching queries.  I can see in Dremio that all queries used reflection.

Running the reference x5 gave these results:

```
$ ./runcurl.sh -server_reference -study_mskimpact -filter_none 
we are about to go here : 'https://dremio-prototype-reference.cbioportal.aws.mskcc.org/api/clinical-data-bin-counts/fetch?dataBinMethod=STATIC'
processing time was : 11.254241
processing time was : 11.388330
processing time was : 11.378099
processing time was : 11.286918
processing time was : 11.061884

Now with the prototype (with all fields included in the reflection):
$ ./runcurl.sh -server_prototype -study_mskimpact -filter_none
we are about to go here : 'https://dremio-prototype.cbioportal.aws.mskcc.org/api/clinical-data-bin-counts/fetch?dataBinMethod=STATIC'
processing time was : 19.715874
processing time was : 21.241977
processing time was : 20.805259
processing time was : 19.591891
processing time was : 19.742534

I modified runcurl.sh so that it writes output to different files depending on the host we are querying.  I confirmed that the reference portal and the prototype portal return the exact same results:

$ zcat data-bin-counts-reference.gz > data-bin-counts-reference.txt
$ zcat data-bin-counts-prototype.gz > data-bin-counts-prototype.txt
$ diff data-bin-counts-reference.txt data-bin-counts-prototype.txt 

(I also ran zdiff which said the same, but I wanted to look at them!)
