### ISSUE TITLE
Fix Lehigh Cohort

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#933]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Lehigh cohort imports successfully overnight
## Technical Description (How are we going to achieve the above)
Mergining in archer samples seems to introduce records in the gene matrix file that do not have panels associated for mutations - throwing error on import. Determine if a value IS needed or if we need to put in an exception

**Comment by sheridancbio** [comment]
Lehigh Valley successfully imported since August 19th .. seems to have been fixed successfully.
