### ISSUE TITLE
Missing Germline Variants for Normals

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#936]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Subhi has a list of samples which are missing from the portal - confirm that these are being pulled and why they are being lost 

Chai Bandlamudi is also missing a BRCA2 variant for patient P-0054696.  I wonder if there is a systematic issue with germline variant pull (Ben)

## Potential Issues
potential consent issue?

**Comment by sheridancbio** [comment]
We received a list of normal samples for the involved patients and attempted to requeue them. About 25 samples were provided and after attempting to requeue, 23 were on the queue for tomorrow. However, 2 failed to requeue [after 3 attempts]. This was reported to Nihir.

**Comment by sheridancbio** [comment]
In addition, we looked yesterday at the 12-245 part-c consent status for these samples. They all were "YES"/True (meaning patients have given part-c consent for germline data sharing.

**Comment by sheridancbio** [comment]
I have done a raw fetch of these germline samples and compared them to what Subhi reported as missing. The large majority of the events *were* present in the fetch so they should get imported tomorrow. There were 2 cases where no events came down even though Subhi reported missing events.

**Comment by sheridancbio** [comment]
Successful requeues were reported to Subhi for validation

**Comment by sheridancbio** [comment]
We spot checked a couple of cases and the germline variants were present in the cbioportal today after requeueing yesterday.

**Comment by sheridancbio** [comment]
Subhi was informed.
