### ISSUE TITLE
Requeueing Germline Samples

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#945]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Part A and Part C consent status should be aligned between CVR and cBioPortal systems.

Note - better understanding of [cvr_consent_status_checker.py ](https://github.com/knowledgesystems/cmo-pipelines/blob/master/import-scripts/cvr_consent_status_checker.py) should be done.  How does data_clinical files get updated when there is a difference between "consent URLs" and data clinical files?

## Technical Description (How are we going to achieve the above)

Multiple endpoints are used to get consent status for CVR.  The lynx cvr-json endpoint with "genomic" data, but also the following endpoints just for consent status:

http://draco.mskcc.org:9890/get_12245_list_parta
http://draco.mskcc.org:9890/get_12245_list_partc

The latter are used to get updates to consent status samples have not been requeued.  Consent status values per Mihir are different from what we get out of all these CVR endpoints.  

## Dependencies 

CVR team

**Comment by sheridancbio** [comment]
still needed:
- [ ] verify that the partc consent corrections are incorporated
- [ ] requeue all normal samples for patients who's partc consent status was incorrectly NO but was corrected to YES

**Comment by sheridancbio** [comment]
I've slacked Mihir with the combined list of affected patients who need normal sample requeue (combination of mskimpact, hemepact, access)

**Comment by sheridancbio** [comment]
Mihir sent back a list of normal samples and we compared against the combined set of patients who needed to be requeued. Issue #1 : these two patients were mentioned on Mihir's response, but they not part of the querey.
> P-0055905
> P-0068701

**Comment by sheridancbio** [comment]
Issue #2 : there were about 500 patients who were requested for normals but were not present in the response from Mihir .. which seems surprising. But we have no easy way to check for this.

**Comment by sheridancbio** [comment]
I worked with @mandawilson tonight and requeued 1724 of the 1726 samples on the normal list from Mihir. The two failures were also reported to him in slack.

**Comment by averyniceday** [comment]
Check that the requeued samples have germline events
