### ISSUE TITLE
Double Check Imports Rules for SV Data

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#948]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
Confirm minimum required fields - whether code matches expectations and add integration tests.

Coordinate with Olegeur and curation team

**Comment by mandawilson** [comment]
I need to make a PR but changes can be seen here: https://github.com/cBioPortal/cbioportal/compare/master...mandawilson:add-test-for-invalid-entrez-gene-id?expand=1

Curators want a record with one invalid gene id (Hugo or Entrez) and one valid to still be imported, but the invalid gene will be null.

**Comment by mandawilson** [comment]
https://github.com/cBioPortal/cbioportal/pull/9803
