### ISSUE TITLE
Document the equivalence of runtime data results

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#956]
Manda has confirmed equivalent data output for a single query (the mskimpact data-bin-counts endpoint on the full data set (88k samples) from the api. To complete this effort we will :
- [ ] try a variety of queries (multi-study, various collections of attribId) and document some details of the data returns and their equivalence (record counts, # samples involved, whatever)
- [ ] look not only at the api output, but look at the returned List<ClinicalData> at the persistence layer interface. There seems to be some difference in content (even if only order) which is causing the prototype service/controller layer to run more slowly (x2).
- [ ] make sure we are covering all the persistence calls that the clinical-bin-count api endpoint is relying on (there were 3 core ... were they all implemented?)

**Comment by mandawilson** [comment]
All curl queries that work in our Dremio-prototype match our reference prototype:

[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_mskimpact--filter_none.gz data-bin-counts--server_reference--study_mskimpact--filter_none.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_mskimpact--filter_age.gz data-bin-counts--server_reference--study_mskimpact--filter_age.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_mskimpact--filter_krasmutation.gz data-bin-counts--server_reference--study_mskimpact--filter_krasmutation.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_mskimpact--filter_two.gz data-bin-counts--server_reference--study_mskimpact--filter_two.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_two--filter_none.gz data-bin-counts--server_reference--study_two--filter_none.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_two--filter_krasmutation.gz data-bin-counts--server_reference--study_two--filter_krasmutation.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_two--filter_two.gz data-bin-counts--server_reference--study_two--filter_two.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_five--filter_none.gz data-bin-counts--server_reference--study_five--filter_none.gz
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ diff data-bin-counts--server_prototype--study_five--filter_krasmutation.gz data-bin-counts--server_reference--study_five--filter_krasmutation.gz

There are two curl queries that still do not work in our Dremio prototype:

-rw-rw-r-- 1 cbioportal_importer cbioportal_importer    0 Oct 14 08:40 data-bin-counts--server_prototype--study_five--filter_age.gz
-rw-rw-r-- 1 cbioportal_importer cbioportal_importer    0 Oct 14 08:42 data-bin-counts--server_prototype--study_five--filter_two.gz

**Comment by mandawilson** [comment]
Running 

```
{"attributes":[{"attributeId":"MUTATION_COUNT","disableLogScale":false,"showNA":true},{"attributeId":"FRACTION_GENOME_ALTERED","disableLogScale":false,"showNA":true},{"attributeId":"CVR_TMB_SCORE","disableLogScale":false,"showNA":true},{"attributeId":"MSI_SCORE","disableLogScale":false,"showNA":true},{"attributeId":"OS_MONTHS","disableLogScale":false,"showNA":true},{"attributeId":"AGE_CURRENT","disableLogScale":false,"showNA":true},{"attributeId":"SAMPLE_COVERAGE","disableLogScale":false,"showNA":true},{"attributeId":"TREATMENT_SCHEDULE","disableLogScale":false,"showNA":true},{"attributeId":"PRIOR_TREATMENT_OF_CYTOTOXIC_CHEMOTHERAPY","disableLogScale":false,"showNA":true}],"studyViewFilter":{"clinicalDataFilters":[{"attributeId":"AGE_CURRENT","values":[{"start":55,"end":60}]}],"studyIds":["mskimpact","bone_ddpcr_shuklan_2018","bladder_merge_msk_2017","crc_met_organoids_2021","nsclc_mskcc_2015"],"alterationFilter":{"copyNumberAlterationEventTypes":{"AMP":true,"HOMDEL":true},"mutationEventTypes":{"any":true},"structuralVariants":null,"includeDriver":true,"includeVUS":true,"includeUnknownOncogenicity":true,"includeUnknownTier":true,"includeGermline":true,"includeSomatic":true,"includeUnknownStatus":true,"tiersBooleanMap":{}}}}{"attributes":[{"attributeId":"MUTATION_COUNT","disableLogScale":false,"showNA":true},{"attributeId":"FRACTION_GENOME_ALTERED","disableLogScale":false,"showNA":true},{"attributeId":"CVR_TMB_SCORE","disableLogScale":false,"showNA":true},{"attributeId":"MSI_SCORE","disableLogScale":false,"showNA":true},{"attributeId":"OS_MONTHS","disableLogScale":false,"showNA":true},{"attributeId":"AGE_CURRENT","disableLogScale":false,"showNA":true},{"attributeId":"SAMPLE_COVERAGE","disableLogScale":false,"showNA":true},{"attributeId":"TREATMENT_SCHEDULE","disableLogScale":false,"showNA":true},{"attributeId":"PRIOR_TREATMENT_OF_CYTOTOXIC_CHEMOTHERAPY","disableLogScale":false,"showNA":true}],"studyViewFilter":{"clinicalDataFilters":[{"attributeId":"AGE_CURRENT","values":[{"start":55,"end":60}]}],"studyIds":["mskimpact","bone_ddpcr_shuklan_2018","bladder_merge_msk_2017","crc_met_organoids_2021","nsclc_mskcc_2015"],"alterationFilter":{"copyNumberAlterationEventTypes":{"AMP":true,"HOMDEL":true},"mutationEventTypes":{"any":true},"structuralVariants":null,"includeDriver":true,"includeVUS":true,"includeUnknownOncogenicity":true,"includeUnknownTier":true,"includeGermline":true,"includeSomatic":true,"includeUnknownStatus":true,"tiersBooleanMap":{}}}}
``` 
http://dremio-prototype.cbioportal.aws.mskcc.org/api/swagger-ui.html?urls.primaryName=internal#/Study%20View/fetchClinicalDataBinCountsUsingPOST

Gives: 504 Error: GATEWAY_TIMEOUT

Same error for 
```
{"attributes":[{"attributeId":"MUTATION_COUNT","disableLogScale":false,"showNA":true},{"attributeId":"FRACTION_GENOME_ALTERED","disableLogScale":false,"showNA":true},{"attributeId":"CVR_TMB_SCORE","disableLogScale":false,"showNA":true},{"attributeId":"MSI_SCORE","disableLogScale":false,"showNA":true},{"attributeId":"OS_MONTHS","disableLogScale":false,"showNA":true},{"attributeId":"AGE_CURRENT","disableLogScale":false,"showNA":true},{"attributeId":"SAMPLE_COVERAGE","disableLogScale":false,"showNA":true},{"attributeId":"TREATMENT_SCHEDULE","disableLogScale":false,"showNA":true},{"attributeId":"PRIOR_TREATMENT_OF_CYTOTOXIC_CHEMOTHERAPY","disableLogScale":false,"showNA":true}],"studyViewFilter":{"clinicalDataFilters":[{"attributeId":"AGE_CURRENT","values":[{"start":55,"end":60}]}],"geneFilters":[{"molecularProfileIds":["mskimpact_mutations","bone_ddpcr_shuklan_2018_mutations","bladder_merge_msk_2017_mutations","crc_met_organoids_2021_mutations","nsclc_mskcc_2015_mutations"],"geneQueries":[[{"hugoGeneSymbol":"KRAS","entrezGeneId":0,"alterations":[],"includeDriver":true,"includeVUS":true,"includeUnknownOncogenicity":true,"tiersBooleanMap":{},"includeUnknownTier":true,"includeGermline":true,"includeSomatic":true,"includeUnknownStatus":true}]]}],"studyIds":["mskimpact","bone_ddpcr_shuklan_2018","bladder_merge_msk_2017","crc_met_organoids_2021","nsclc_mskcc_2015"],"alterationFilter":{"copyNumberAlterationEventTypes":{"AMP":true,"HOMDEL":true},"mutationEventTypes":{"any":true},"structuralVariants":null,"includeDriver":true,"includeVUS":true,"includeUnknownOncogenicity":true,"includeUnknownTier":true,"includeGermline":true,"includeSomatic":true,"includeUnknownStatus":true,"tiersBooleanMap":{}}}}
```
