### ISSUE TITLE
Complete and summarize runtime comparison

### ISSUE THREAD

**Issue by sheridancbio** [knowledgesystems/pipelines-scrum#957]

**Comment by sheridancbio** [comment]
We see equivalent dremio performance on the ClinicalDataRepostiory function entry/exit, but service/controller layers seem slower. (x2). This may improve if the persistence layer data examination (see #956) reveals something we can fix or optimize in Dremio. But in any case, we should capture runtime performance measurements over a range of test cases (vary study size, selected sample count, # of clinical attributes profiled, etc). Currently we have only measured the run times of the API response (round trip) and the entry/exit of the persistence layer functions. We must make sure:
- [ ] all core dependencies of the clinical-bin-count api endpoint have been implemented in Dremio (exclude the study view filter applier)
- [ ] persistence layer function implementation runtimes are captured for a variety of inputs (# of studies, # of clinical attr ids, sample select list size) for each dependent persistence layer function
- [ ] if performance on dremio prototype system is more than 50% longer than the reference, a reasonable attempt at speedup has been attempted (reflection with partition key for study)
- [ ] we have gone over the configuration and asked / probed whether caching is distorting the results at any point of the runtime evaluation. Manda has already confirmed that our rds node hosting the mysql database is not using ram caching of query results. We also have no persistence cache on the portal. We should ask whether caching in dremio or in the cbioportal codebase itself might be interfering and be moderately confident that it is not.

**Comment by sheridancbio** [comment]
After examining the logs of the prototype, it seems as though getPatientClinicalDataDetailedToSample() is always called for the set of requested samples during the final application of the study view filter. (Not only when there is an ambiguous case clinical attribute which is a patient attribute in one study of the query and a sample attribute for another study of the query).
So the conclusion is that this is needed for satisfying the request (we are still uncertain if it is needed for generating the bin counts .. or for filtering the bin counts)

**Comment by mandawilson** [comment]
These are the timings for the 2 prototype curl queries that get a GATEWAY_TIMEOUT:

StudyViewFilterApplier.apply()	0.136
StudyViewFilterApplier.apply()	0.135
StudyViewFilterApplier.apply()	0.117
StudyViewFilterApplier.apply()	0.21
StudyViewFilterApplier.apply()	0.25
ClinicalDataMyBatisRepository.fetchClinicalDataCounts()	0.984
ClinicalDataMyBatisRepository.fetchClinicalDataCounts()	0.632
StudyViewFilterApplier.apply()	0.106
StudyViewFilterApplier.apply()	0.106
StudyViewFilterApplier.apply()	0.122
StudyViewFilterApplier.apply()	0.127
ClinicalDataMyBatisRepository.fetchClinicalData()	74.452
ClinicalDataServiceImpl.fetchClinicalData()	74.453
ClinicalDataMyBatisRepository.fetchClinicalData()	75.422
ClinicalDataServiceImpl.fetchClinicalData()	75.423
ClinicalDataMyBatisRepository.fetchClinicalData()	135.133
ClinicalDataServiceImpl.fetchClinicalData()	135.135
ClinicalDataMyBatisRepository.fetchClinicalData()	1.216
ClinicalDataServiceImpl.fetchClinicalData()	1.217
StudyViewController.fetchClinicalDataBinCounts()	137.5
StudyViewFilterApplier.apply()	0.677
ClinicalDataMyBatisRepository.fetchClinicalData()	17.794
ClinicalDataServiceImpl.fetchClinicalData()	17.796
ClinicalDataMyBatisRepository.fetchClinicalData()	10.333
ClinicalDataServiceImpl.fetchClinicalData()	10.335
ClinicalDataMyBatisRepository.fetchClinicalData()	21.92
ClinicalDataServiceImpl.fetchClinicalData()	21.921
ClinicalDataMyBatisRepository.fetchClinicalData()	12.023
StudyViewFilterApplier.apply()	39.962
StudyViewController.fetchClinicalDataBinCounts()	79.823
StudyViewFilterApplier.apply()	0.706
ClinicalDataMyBatisRepository.fetchClinicalData()	18.984
ClinicalDataServiceImpl.fetchClinicalData()	18.985
ClinicalDataMyBatisRepository.fetchClinicalData()	13.481
ClinicalDataServiceImpl.fetchClinicalData()	13.483
ClinicalDataMyBatisRepository.fetchClinicalData()	21.428
ClinicalDataServiceImpl.fetchClinicalData()	21.428
ClinicalDataMyBatisRepository.fetchClinicalData()	12.376
StudyViewFilterApplier.apply()	40.415
StudyViewController.fetchClinicalDataBinCounts()	82.033

**Comment by mandawilson** [comment]
==> curl-timings-output--server_prototype--study_mskimpact--filter_none <==
     time_namelookup:  0.003213s
        time_connect:  0.003488s
     time_appconnect:  0.010741s
    time_pretransfer:  0.010775s
       time_redirect:  0.000000s
  time_starttransfer:  19.329100s
                     ----------
          time_total:  19.329195s

==> curl-timings-output--server_reference--study_mskimpact--filter_none <==
     time_namelookup:  0.003030s
        time_connect:  0.004026s
     time_appconnect:  0.011207s
    time_pretransfer:  0.011242s
       time_redirect:  0.000000s
  time_starttransfer:  12.691716s
                     ----------
          time_total:  12.691808s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_mskimpact--filter_age
==> curl-timings-output--server_prototype--study_mskimpact--filter_age <==
     time_namelookup:  0.003089s
        time_connect:  0.003370s
     time_appconnect:  0.010484s
    time_pretransfer:  0.010521s
       time_redirect:  0.000000s
  time_starttransfer:  33.170059s
                     ----------
          time_total:  33.170153s

==> curl-timings-output--server_reference--study_mskimpact--filter_age <==
     time_namelookup:  0.002278s
        time_connect:  0.002543s
     time_appconnect:  0.010329s
    time_pretransfer:  0.010364s
       time_redirect:  0.000000s
  time_starttransfer:  16.190746s
                     ----------
          time_total:  16.190845s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_mskimpact--filter_krasmutation
==> curl-timings-output--server_prototype--study_mskimpact--filter_krasmutation <==
     time_namelookup:  0.003101s
        time_connect:  0.003448s
     time_appconnect:  0.011163s
    time_pretransfer:  0.011202s
       time_redirect:  0.000000s
  time_starttransfer:  21.836894s
                     ----------
          time_total:  21.836984s

==> curl-timings-output--server_reference--study_mskimpact--filter_krasmutation <==
     time_namelookup:  0.003017s
        time_connect:  0.003346s
     time_appconnect:  0.010553s
    time_pretransfer:  0.010591s
       time_redirect:  0.000000s
  time_starttransfer:  12.991671s
                     ----------
          time_total:  12.991765s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_mskimpact--filter_two
==> curl-timings-output--server_prototype--study_mskimpact--filter_two <==
     time_namelookup:  0.001967s
        time_connect:  0.002324s
     time_appconnect:  0.009953s
    time_pretransfer:  0.009988s
       time_redirect:  0.000000s
  time_starttransfer:  32.060908s
                     ----------
          time_total:  32.061000s

==> curl-timings-output--server_reference--study_mskimpact--filter_two <==
     time_namelookup:  0.002344s
        time_connect:  0.002631s
     time_appconnect:  0.009791s
    time_pretransfer:  0.009830s
       time_redirect:  0.000000s
  time_starttransfer:  15.406815s
                     ----------
          time_total:  15.406908s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_two--filter_none
==> curl-timings-output--server_prototype--study_two--filter_none <==
     time_namelookup:  0.003538s
        time_connect:  0.003841s
     time_appconnect:  0.011306s
    time_pretransfer:  0.011344s
       time_redirect:  0.000000s
  time_starttransfer:  36.867912s
                     ----------
          time_total:  36.868011s

==> curl-timings-output--server_reference--study_two--filter_none <==
     time_namelookup:  0.003335s
        time_connect:  0.003607s
     time_appconnect:  0.018557s
    time_pretransfer:  0.018598s
       time_redirect:  0.000000s
  time_starttransfer:  16.479352s
                     ----------
          time_total:  16.479447s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_two--filter_krasmutation
==> curl-timings-output--server_prototype--study_two--filter_krasmutation <==
     time_namelookup:  0.003187s
        time_connect:  0.003452s
     time_appconnect:  0.010648s
    time_pretransfer:  0.010687s
       time_redirect:  0.000000s
  time_starttransfer:  46.033926s
                     ----------
          time_total:  46.034015s

==> curl-timings-output--server_reference--study_two--filter_krasmutation <==
     time_namelookup:  0.003285s
        time_connect:  0.003582s
     time_appconnect:  0.010693s
    time_pretransfer:  0.010730s
       time_redirect:  0.000000s
  time_starttransfer:  23.769265s
                     ----------
          time_total:  23.769360s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_two--filter_two
==> curl-timings-output--server_prototype--study_two--filter_two <==
     time_namelookup:  0.002698s
        time_connect:  0.003009s
     time_appconnect:  0.013298s
    time_pretransfer:  0.013342s
       time_redirect:  0.000000s
  time_starttransfer:  43.569289s
                     ----------
          time_total:  43.569380s

==> curl-timings-output--server_reference--study_two--filter_two <==
     time_namelookup:  0.002891s
        time_connect:  0.003753s
     time_appconnect:  0.011920s
    time_pretransfer:  0.011958s
       time_redirect:  0.000000s
  time_starttransfer:  24.223843s
                     ----------
          time_total:  24.223935s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_five--filter_none
==> curl-timings-output--server_prototype--study_five--filter_none <==
     time_namelookup:  0.003557s
        time_connect:  0.006791s
     time_appconnect:  0.014104s
    time_pretransfer:  0.014147s
       time_redirect:  0.000000s
  time_starttransfer:  36.246212s
                     ----------
          time_total:  36.246302s

==> curl-timings-output--server_reference--study_five--filter_none <==
     time_namelookup:  0.002749s
        time_connect:  0.003023s
     time_appconnect:  0.010127s
    time_pretransfer:  0.010164s
       time_redirect:  0.000000s
  time_starttransfer:  19.626253s
                     ----------
          time_total:  19.626344s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ tail -n +1 *--study_five--filter_krasmutation
==> curl-timings-output--server_prototype--study_five--filter_krasmutation <==
     time_namelookup:  0.003534s
        time_connect:  0.003830s
     time_appconnect:  0.010994s
    time_pretransfer:  0.011027s
       time_redirect:  0.000000s
  time_starttransfer:  45.163635s
                     ----------
          time_total:  45.163695s

==> curl-timings-output--server_reference--study_five--filter_krasmutation <==
     time_namelookup:  0.003016s
        time_connect:  0.003923s
     time_appconnect:  0.011360s
    time_pretransfer:  0.011397s
       time_redirect:  0.000000s
  time_starttransfer:  27.812425s
                     ----------
          time_total:  27.812516s

**Comment by mandawilson** [comment]
And the 2 queries that we get a timeout for in the prototype (after 59 seconds?) have these times:

[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ cat curl-timings-output--server_reference--study_five--filter_age 
     time_namelookup:  0.003163s
        time_connect:  0.003487s
     time_appconnect:  0.011383s
    time_pretransfer:  0.011422s
       time_redirect:  0.000000s
  time_starttransfer:  36.349032s
                     ----------
          time_total:  36.349125s
[cbioportal_importer@ip-10-1-21-42 dremio-prototype]$ cat curl-timings-output--server_reference--study_five--filter_two 
     time_namelookup:  0.003305s
        time_connect:  0.003576s
     time_appconnect:  0.012030s
    time_pretransfer:  0.012064s
       time_redirect:  0.000000s
  time_starttransfer:  33.258367s
                     ----------
          time_total:  33.258454s

**Comment by mandawilson** [comment]
Trying study_two--filter_krasmutation multiple times on prototype:

1) timeout - probably engine warming up after not being queried for a bit
2) time_total:  40.924179s
3) time_total:  42.880215s
4) time_total:  42.269750s
5) time_total:  41.214462s
6) time_total:  42.096070s
7) time_total:  42.233935s
8) time_total:  42.522232s
9) time_total:  40.198700s
10) time_total:  41.291873s

Trying study_two--filter_krasmutation multiple times on reference:

1) time_total:  25.420445s
2) time_total:  24.662326s
3) time_total:  24.655102s
4) time_total:  23.487304s
5) time_total:  23.924088s
6) time_total:  23.893204s
7) time_total:  24.127082s
8) time_total:  24.170280s
9) time_total:  24.524692s
10) time_total:  23.831168s
