### ISSUE TITLE
Review Lukes PR to remove cBIoPortal dependencies from GN annotation pipeline.

### ISSUE THREAD

**Issue by n1zea144** [knowledgesystems/pipelines-scrum#981]
https://github.com/genome-nexus/genome-nexus-annotation-pipeline/pull/230
https://github.com/cBioPortal/cbioportal/pull/9835

We need to update our import pipeline to import cBioPortal directly.  When this is done, the following PRs can be merged.

 Add following dependencies to pipelines to test:
- MafUtil
- Genome Nexus Annotation Pipeline
- cBioPortal Core

whereas previously everything that was pulled in was under Genome Nexus Annotation Pipeline

**Comment by averyniceday** [comment]
Dependency works - but can't make PR yet because Luke needs to separate the maf util out into an actual repo or submodule
