### ISSUE TITLE
Debug GENIE Import 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#990]
## Client (Who is making the request)
Curation
## Issue/Deliverable
Finish GENIE private import 
## Urgency (same day/ same week/ no immediate need)
High

**Comment by sheridancbio** [comment]
Genie import failed 3 times over the weekend when launched at the 3pm crontab start. Looking at the logs, the memory usage of the mysqld process dropped to zero percent at 6:10 pm Sunday. The import of genie had started at 3pm and it failed at 00:45 early Monday (the JDBC error about rollback not possible after closing connection).

**Comment by sheridancbio** [comment]
another import of genie was started at 9am and failed around 11:26am during mutation import. No other import processes appeared to be running at that time, but the free memory on the system (reported by vmstat) increased unexpectedly at 11:20 (through 11:40). It is hard to tell whether the system was freeing memory, a large non-import process was cleared from memory, or whether the genie importer run process ran a (java vm) garbage collection..

Given that we have had multiple failures for this study recently and one just this morning where things were quiet (not dmp run in progress), I think we should prioritize getting the node in the knowlegesystems aws account up and running.

**Comment by sheridancbio** [comment]
Another attempt at genie_private import succeeded from the normal pipeline (>20 hours). This card is complete, but the effort to build an importer node in the knowledgesystems account continues.
