### ISSUE TITLE
Integrate AZ Repo into Overnight Scripts 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#993]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
- [ ] Pull
- [ ] Copy solid heme data into AZ clone
- [ ] Filter 12-245 PartC
- [ ] Generate Report
- [ ] Push

**Comment by callachennault** [comment]
Pull Request: https://github.com/knowledgesystems/cmo-pipelines/pull/974
