### ISSUE TITLE
Implement Germline Fetch Calls 

### ISSUE THREAD

**Issue by averyniceday** [knowledgesystems/pipelines-scrum#998]
## Done Condition (What do we need? Why do we need it? Keep this is small as possible!)
MPath Proxy sends repeated calls to germline endpoint and is able to construct a message containing germline variants (per sample) - if seg data is added, should include this functionality

**Comment by mandawilson** [comment]
Seg step is not called by germline pipeline.

**Comment by mandawilson** [comment]
https://github.com/averyniceday/mpath-proxy/pull/2
